.TH "block" 3 "2023年 一月 25日 星期三" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
block
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <block\&.hpp>\fP
.SS "Protected 属性"

.in +1c
.ti -1c
.RI "std::string \fBcustomName\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 \fBblock\&.hpp\fP 第 \fB6\fP 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "std::string block::customName\fC [protected]\fP"

.PP
在文件 \fBblock\&.hpp\fP 第 \fB9\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Freecraft 的 源代码自动生成\&.
