.TH "src/fcenums.hpp" 3 "2023年 一月 25日 星期三" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fcenums.hpp
.SH SYNOPSIS
.br
.PP
.SS "枚举"

.in +1c
.ti -1c
.RI "enum class \fBfcEnum\fP "
.br
.in -1c
.SH "枚举类型说明"
.PP 
.SS "enum class \fBfcEnum\fP\fC [strong]\fP"

.PP
在文件 \fBfcenums\&.hpp\fP 第 \fB4\fP 行定义\&..PP
.nf
5 {
6     
7 };
.fi

.SH "作者"
.PP 
由 Doyxgen 通过分析 Freecraft 的 源代码自动生成\&.
