.TH "src/fcexceptions.hpp" 3 "2023年 一月 25日 星期三" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fcexceptions.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <exception>\fP
.br
\fC#include 'fcenums\&.hpp'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBfcRuntimeException\fP"
.br
.ti -1c
.RI "class \fBfcRuntimeError\fP"
.br
.ti -1c
.RI "class \fBfcCalcException\fP"
.br
.ti -1c
.RI "class \fBfcDivisionZeroException\fP"
.br
.ti -1c
.RI "class \fBfcSyntaxException\fP"
.br
.ti -1c
.RI "class \fBfcArrayIndexOutOfBoundException\fP"
.br
.in -1c
.SS "类型定义"

.in +1c
.ti -1c
.RI "typedef std::exception \fBfcexception\fP"
.br
.in -1c
.SH "类型定义说明"
.PP 
.SS "typedef std::exception \fBfcexception\fP"

.PP
在文件 \fBfcexceptions\&.hpp\fP 第 \fB7\fP 行定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 Freecraft 的 源代码自动生成\&.
