.TH "fcg" 3 "2023年 一月 25日 星期三" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fcg
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "void \fBreadGLSL\fP (const char *fileName, std::string &str)"
.br
.ti -1c
.RI "void \fBcompileGLSL\fP (const GLchar *const *glsl, GLuint &shader, GLenum type)"
.br
.in -1c
.SH "函数说明"
.PP 
.SS "void fcg::compileGLSL (const GLchar *const * glsl, GLuint & shader, GLenum type)"

.SS "void fcg::readGLSL (const char * fileName, std::string & str)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 Freecraft 的 源代码自动生成\&.
