.TH "src/graphics/fcglsl.hpp" 3 "2023年 一月 25日 星期三" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/graphics/fcglsl.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'glad/glad\&.h'\fP
.br
\fC#include 'glfw/glfw3\&.h'\fP
.br

.SS "命名空间"

.in +1c
.ti -1c
.RI "namespace \fBfcg\fP"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "void \fBfcg::readGLSL\fP (const char *fileName, std::string &str)"
.br
.ti -1c
.RI "void \fBfcg::compileGLSL\fP (const GLchar *const *glsl, GLuint &shader, GLenum type)"
.br
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 Freecraft 的 源代码自动生成\&.
