.TH "src/graphics/fcglsl.cpp" 3 "2023年 一月 25日 星期三" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/graphics/fcglsl.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'fcglsl\&.hpp'\fP
.br

.SH "详细描述"
.PP 

.PP
\fB作者\fP
.RS 4
Promesis (m3149154722@outlook.com) 
.RE
.PP
\fB版本\fP
.RS 4
0\&.1 
.RE
.PP
\fB日期\fP
.RS 4
2023-01-21
.RE
.PP
Promesis 2023 the Freecraft dev 
.PP
在文件 \fBfcglsl\&.cpp\fP 中定义\&.
.SH "作者"
.PP 
由 Doyxgen 通过分析 Freecraft 的 源代码自动生成\&.
