.TH "fcSyntaxException" 3 "2023年 一月 25日 星期三" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fcSyntaxException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fcexceptions\&.hpp>\fP
.PP
继承自 \fBfcRuntimeException\fP \&.
.SS "Public 成员函数"

.in +1c
.ti -1c
.RI "\fBfcSyntaxException\fP (const char *whyException='the syntax isn't right')"
.br
.in -1c

Public 成员函数 继承自 \fBfcRuntimeException\fP
.in +1c
.ti -1c
.RI "\fBfcRuntimeException\fP (const char *whyException='runtime exception occured')"
.br
.ti -1c
.RI "const char * \fBwhat\fP ()"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 \fBfcexceptions\&.hpp\fP 第 \fB46\fP 行定义\&.
.SH "构造及析构函数说明"
.PP 
.SS "fcSyntaxException::fcSyntaxException (const char * whyException = \fC'the syntax isn't right'\fP)\fC [inline]\fP"

.PP
在文件 \fBfcexceptions\&.hpp\fP 第 \fB49\fP 行定义\&..PP
.nf
49 : fcRuntimeException(whyException) {};
.fi


.SH "作者"
.PP 
由 Doyxgen 通过分析 Freecraft 的 源代码自动生成\&.
