.TH "gamesave" 3 "2023年 一月 25日 星期三" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gamesave
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gamesave\&.hpp>\fP
.SS "Public 属性"

.in +1c
.ti -1c
.RI "\fBfcGamesaveMode\fP \fBfilemode\fP"
.br
.ti -1c
.RI "std::filesystem::path \fBworldInfoFile\fP"
.br
.ti -1c
.RI "std::filesystem::path \fBplayerDataDirectory\fP"
.br
.ti -1c
.RI "std::filesystem::path \fBchunksFilesDirectory\fP"
.br
.in -1c
.SH "详细描述"
.PP 
在文件 \fBgamesave\&.hpp\fP 第 \fB26\fP 行定义\&.
.SH "类成员变量说明"
.PP 
.SS "std::filesystem::path gamesave::chunksFilesDirectory"

.PP
在文件 \fBgamesave\&.hpp\fP 第 \fB31\fP 行定义\&.
.SS "\fBfcGamesaveMode\fP gamesave::filemode"

.PP
在文件 \fBgamesave\&.hpp\fP 第 \fB28\fP 行定义\&.
.SS "std::filesystem::path gamesave::playerDataDirectory"

.PP
在文件 \fBgamesave\&.hpp\fP 第 \fB30\fP 行定义\&.
.SS "std::filesystem::path gamesave::worldInfoFile"

.PP
在文件 \fBgamesave\&.hpp\fP 第 \fB29\fP 行定义\&.

.SH "作者"
.PP 
由 Doyxgen 通过分析 Freecraft 的 源代码自动生成\&.
