.TH "src/data/item/item.hpp" 3 "2023年 一月 25日 星期三" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/data/item/item.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'json/json\&.h'\fP
.br
\fC#include 'glad/glad\&.h'\fP
.br
\fC#include 'GLFW/glfw3\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include '\&.\&./uuid/uuid\&.hpp'\fP
.br

.SS "类"

.in +1c
.ti -1c
.RI "class \fBfcitem\fP"
.br
.RI "defines item\&. "
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 Freecraft 的 源代码自动生成\&.
