uuid.cpp
char uitchex(unsigned int i)
Referenced by uuid::setrandomly.
bool ishexnum(char ch)
Referenced by checksyntax.
bool checksyntax(const Json::String &str)
References ishexnum.
Referenced by uuid::uuid.
bool operator==(const Json::String &datL, const uuid &datR)
reversed. dat dat true false
References uuid::data.