.TH "block" 3 "Wed Jan 25 2023" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
block
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <block\&.hpp>\fP
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBcustomName\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBblock\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::string block::customName\fC [protected]\fP"

.PP
Definition at line \fB9\fP of file \fBblock\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Freecraft from the source code\&.
