.TH "src Directory Reference" 3 "Wed Jan 25 2023" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdata\fP"
.br
.ti -1c
.RI "directory \fBglad\fP"
.br
.ti -1c
.RI "directory \fBgraphics\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfcenums\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfcexceptions\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.in -1c
