.TH "src/fcenums.hpp" 3 "Wed Jan 25 2023" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fcenums.hpp
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBfcEnum\fP "
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBfcEnum\fP\fC [strong]\fP"

.PP
Definition at line \fB4\fP of file \fBfcenums\&.hpp\fP\&..PP
.nf
5 {
6     
7 };
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Freecraft from the source code\&.
