.TH "src/fcexceptions.hpp" 3 "Wed Jan 25 2023" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fcexceptions.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <exception>\fP
.br
\fC#include 'fcenums\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBfcRuntimeException\fP"
.br
.ti -1c
.RI "class \fBfcRuntimeError\fP"
.br
.ti -1c
.RI "class \fBfcCalcException\fP"
.br
.ti -1c
.RI "class \fBfcDivisionZeroException\fP"
.br
.ti -1c
.RI "class \fBfcSyntaxException\fP"
.br
.ti -1c
.RI "class \fBfcArrayIndexOutOfBoundException\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::exception \fBfcexception\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::exception \fBfcexception\fP"

.PP
Definition at line \fB7\fP of file \fBfcexceptions\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Freecraft from the source code\&.
