.TH "src/graphics/fcglsl.cpp" 3 "Wed Jan 25 2023" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/graphics/fcglsl.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'fcglsl\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Promesis (m3149154722@outlook.com) 
.RE
.PP
\fBVersion\fP
.RS 4
0\&.1 
.RE
.PP
\fBDate\fP
.RS 4
2023-01-21
.RE
.PP
Promesis 2023 the Freecraft dev 
.PP
Definition in file \fBfcglsl\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Freecraft from the source code\&.
