.TH "fcRuntimeError" 3 "Wed Jan 25 2023" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fcRuntimeError
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fcexceptions\&.hpp>\fP
.PP
Inherits fcexception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfcRuntimeError\fP (const char *whyError='runtime error occured')"
.br
.ti -1c
.RI "const char * \fBwhat\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const char * \fBwhy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBfcexceptions\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "fcRuntimeError::fcRuntimeError (const char * whyError = \fC'runtime error occured'\fP)\fC [inline]\fP"

.PP
Definition at line \fB25\fP of file \fBfcexceptions\&.hpp\fP\&..PP
.nf
25 : why(whyError) {};
.fi

.SH "Member Function Documentation"
.PP 
.SS "const char * fcRuntimeError::what ()"

.SH "Member Data Documentation"
.PP 
.SS "const char* fcRuntimeError::why\fC [private]\fP"

.PP
Definition at line \fB22\fP of file \fBfcexceptions\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Freecraft from the source code\&.
