.TH "fcRuntimeException" 3 "Wed Jan 25 2023" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fcRuntimeException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fcexceptions\&.hpp>\fP
.PP
Inherits fcexception\&.
.PP
Inherited by \fBfcArrayIndexOutOfBoundException\fP, \fBfcCalcException\fP, and \fBfcSyntaxException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfcRuntimeException\fP (const char *whyException='runtime exception occured')"
.br
.ti -1c
.RI "const char * \fBwhat\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const char * \fBwhy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBfcexceptions\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "fcRuntimeException::fcRuntimeException (const char * whyException = \fC'runtime exception occured'\fP)\fC [inline]\fP"

.PP
Definition at line \fB15\fP of file \fBfcexceptions\&.hpp\fP\&..PP
.nf
15 : why(whyException) {};
.fi

.SH "Member Function Documentation"
.PP 
.SS "const char * fcRuntimeException::what ()"

.SH "Member Data Documentation"
.PP 
.SS "const char* fcRuntimeException::why\fC [private]\fP"

.PP
Definition at line \fB12\fP of file \fBfcexceptions\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Freecraft from the source code\&.
