.TH "fcSyntaxException" 3 "Wed Jan 25 2023" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fcSyntaxException
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fcexceptions\&.hpp>\fP
.PP
Inherits \fBfcRuntimeException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfcSyntaxException\fP (const char *whyException='the syntax isn't right')"
.br
.in -1c

Public Member Functions inherited from \fBfcRuntimeException\fP
.in +1c
.ti -1c
.RI "\fBfcRuntimeException\fP (const char *whyException='runtime exception occured')"
.br
.ti -1c
.RI "const char * \fBwhat\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB46\fP of file \fBfcexceptions\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "fcSyntaxException::fcSyntaxException (const char * whyException = \fC'the syntax isn't right'\fP)\fC [inline]\fP"

.PP
Definition at line \fB49\fP of file \fBfcexceptions\&.hpp\fP\&..PP
.nf
49 : fcRuntimeException(whyException) {};
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Freecraft from the source code\&.
