.TH "FDTData" 3 "Tue Jan 17 2023" "Version 00.01a03-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FDTData \- base class of data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FDTDataType\&.hpp>\fP
.PP
Inherited by \fBFDTFloat\fP, \fBFDTInt\fP, and \fBFDTShort\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBFDTDataTag\fP \fBgetTag\fP (void)=0"
.br
.RI "Get the Tag of object\&. "
.ti -1c
.RI "\fBFDTData\fP (const \fBFDTData\fP &dat)"
.br
.RI "Construct a new \fBFDTData\fP object(copy ctor)\&. "
.ti -1c
.RI "\fBFDTData\fP (\fBFDTData\fP &&datR)"
.br
.RI "Construct a new \fBFDTData\fP object(move ctor)\&. "
.ti -1c
.RI "\fBFDTData\fP (void)"
.br
.RI "Construct a new \fBFDTData\fP object(default ctor)\&. "
.ti -1c
.RI "virtual \fB~FDTData\fP (void)"
.br
.RI "Destroy the \fBFDTData\fP object\&. "
.ti -1c
.RI "virtual const \fBFDTData\fP & \fBoperator=\fP (const \fBFDTData\fP &dat)=0"
.br
.RI "copy assignmemt operator\&. "
.ti -1c
.RI "virtual const \fBFDTData\fP & \fBgetData\fP (void) const =0"
.br
.RI "Get the Data\&. "
.ti -1c
.RI "virtual void \fBsetData\fP (const \fBFDTData\fP &dat)=0"
.br
.RI "Set the Data\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBFDTDataTag\fP \fB_tag\fP"
.br
.RI "tag of current data\&. "
.in -1c
.SH "Detailed Description"
.PP 
base class of data\&. 
.PP
Definition at line \fB54\fP of file \fBFDTDataType\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FDTData::FDTData (const \fBFDTData\fP & dat)"

.PP
Construct a new \fBFDTData\fP object(copy ctor)\&. 
.PP
\fBParameters\fP
.RS 4
\fIdat\fP a const \fBFDTData\fP reference\&. 
.RE
.PP

.SS "FDTData::FDTData (\fBFDTData\fP && datR)"

.PP
Construct a new \fBFDTData\fP object(move ctor)\&. 
.PP
\fBParameters\fP
.RS 4
\fIdatR\fP right value\&. 
.RE
.PP

.SS "FDTData::FDTData (void)"

.PP
Construct a new \fBFDTData\fP object(default ctor)\&. 
.SS "virtual FDTData::~FDTData (void)\fC [virtual]\fP"

.PP
Destroy the \fBFDTData\fP object\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual const \fBFDTData\fP & FDTData::getData (void) const\fC [pure virtual]\fP"

.PP
Get the Data\&. pure virtual function\&.
.PP
\fBReturns\fP
.RS 4
const \fBFDTData\fP& 
.RE
.PP

.PP
Implemented in \fBFDTInt\fP, \fBFDTShort\fP, and \fBFDTFloat\fP\&.
.SS "virtual \fBFDTDataTag\fP FDTData::getTag (void)\fC [pure virtual]\fP"

.PP
Get the Tag of object\&. pure virtual function\&. 
.PP
\fBReturns\fP
.RS 4
FDTDataTag 
.RE
.PP

.PP
Implemented in \fBFDTInt\fP, \fBFDTShort\fP, and \fBFDTFloat\fP\&.
.SS "virtual const \fBFDTData\fP & FDTData::operator= (const \fBFDTData\fP & dat)\fC [pure virtual]\fP"

.PP
copy assignmemt operator\&. pure virtual function\&.
.PP
\fBParameters\fP
.RS 4
\fIdat\fP a const \fBFDTData\fP reference\&. 
.RE
.PP
\fBReturns\fP
.RS 4
const \fBFDTData\fP& 
.RE
.PP

.SS "virtual void FDTData::setData (const \fBFDTData\fP & dat)\fC [pure virtual]\fP"

.PP
Set the Data\&. pure virtual function\&.
.PP
\fBParameters\fP
.RS 4
\fIdat\fP const \fBFDTData\fP reference\&. data to set\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "\fBFDTDataTag\fP FDTData::_tag\fC [protected]\fP"

.PP
tag of current data\&. 
.PP
Definition at line \fB61\fP of file \fBFDTDataType\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Freecraft from the source code\&.
