.TH "FDTInt" 3 "Tue Jan 17 2023" "Version 00.01a03-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FDTInt
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FDTDataType\&.hpp>\fP
.PP
Inherits \fBFDTData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFDTDataTag\fP \fBgetTag\fP (void)"
.br
.RI "Get the Tag of object\&. "
.ti -1c
.RI "\fB~FDTInt\fP (void)"
.br
.RI "Destroy the \fBFDTInt\fP object\&. "
.ti -1c
.RI "\fBFDTInt\fP (int _int=0)"
.br
.RI "Construct a new \fBFDTInt\fP object\&. "
.ti -1c
.RI "\fBFDTInt\fP (const \fBFDTInt\fP &_int)"
.br
.RI "Construct a new \fBFDTInt\fP object\&. "
.ti -1c
.RI "\fBFDTInt\fP (\fBFDTInt\fP &&_intR)"
.br
.RI "Construct a new \fBFDTInt\fP object\&. "
.ti -1c
.RI "const \fBFDTInt\fP & \fBoperator=\fP (const \fBFDTInt\fP &_int)"
.br
.RI "copy assigent operator\&. "
.ti -1c
.RI "const \fBFDTInt\fP & \fBoperator=\fP (\fBFDTInt\fP &&_intR)"
.br
.RI "move assignment operator\&. "
.ti -1c
.RI "const \fBFDTInt\fP & \fBgetData\fP (void) const"
.br
.RI "Get the Data of object\&. "
.ti -1c
.RI "void \fBsetData\fP (const \fBFDTInt\fP &dat)"
.br
.RI "Set the Data of object\&. "
.ti -1c
.RI "\fBoperator int\fP (void) const"
.br
.RI "conversation function\&. "
.in -1c

Public Member Functions inherited from \fBFDTData\fP
.in +1c
.ti -1c
.RI "virtual \fBFDTDataTag\fP \fBgetTag\fP (void)=0"
.br
.RI "Get the Tag of object\&. "
.ti -1c
.RI "\fBFDTData\fP (const \fBFDTData\fP &dat)"
.br
.RI "Construct a new \fBFDTData\fP object(copy ctor)\&. "
.ti -1c
.RI "\fBFDTData\fP (\fBFDTData\fP &&datR)"
.br
.RI "Construct a new \fBFDTData\fP object(move ctor)\&. "
.ti -1c
.RI "\fBFDTData\fP (void)"
.br
.RI "Construct a new \fBFDTData\fP object(default ctor)\&. "
.ti -1c
.RI "virtual \fB~FDTData\fP (void)"
.br
.RI "Destroy the \fBFDTData\fP object\&. "
.ti -1c
.RI "virtual const \fBFDTData\fP & \fBoperator=\fP (const \fBFDTData\fP &dat)=0"
.br
.RI "copy assignmemt operator\&. "
.ti -1c
.RI "virtual const \fBFDTData\fP & \fBgetData\fP (void) const =0"
.br
.RI "Get the Data\&. "
.ti -1c
.RI "virtual void \fBsetData\fP (const \fBFDTData\fP &dat)=0"
.br
.RI "Set the Data\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBdata\fP"
.br
.RI "data if this \fBFDTInt\fP instance\&. "
.in -1c

Protected Attributes inherited from \fBFDTData\fP
.in +1c
.ti -1c
.RI "\fBFDTDataTag\fP \fB_tag\fP"
.br
.RI "tag of current data\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB140\fP of file \fBFDTDataType\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FDTInt::~FDTInt (void)"

.PP
Destroy the \fBFDTInt\fP object\&. 
.SS "FDTInt::FDTInt (int _int = \fC0\fP)"

.PP
Construct a new \fBFDTInt\fP object\&. default ctor\&.
.PP
\fBParameters\fP
.RS 4
\fI_int\fP value to set\&. default is zero\&. 
.RE
.PP

.SS "FDTInt::FDTInt (const \fBFDTInt\fP & _int)"

.PP
Construct a new \fBFDTInt\fP object\&. copy ctor\&.
.PP
\fBParameters\fP
.RS 4
\fI_int\fP object to assign\&. 
.RE
.PP

.SS "FDTInt::FDTInt (\fBFDTInt\fP && _intR)"

.PP
Construct a new \fBFDTInt\fP object\&. move ctor\&.
.PP
\fBParameters\fP
.RS 4
\fI_intR\fP object to assign\&. right val\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "const \fBFDTInt\fP & FDTInt::getData (void) const\fC [virtual]\fP"

.PP
Get the Data of object\&. 
.PP
\fBReturns\fP
.RS 4
const \fBFDTInt\fP& 
.RE
.PP

.PP
Implements \fBFDTData\fP\&.
.SS "\fBFDTDataTag\fP FDTInt::getTag (void)\fC [virtual]\fP"

.PP
Get the Tag of object\&. 
.PP
\fBReturns\fP
.RS 4
FDTDataTag 
.RE
.PP

.PP
Implements \fBFDTData\fP\&.
.SS "FDTInt::operator int (void) const"

.PP
conversation function\&. 
.SS "const \fBFDTInt\fP & FDTInt::operator= (const \fBFDTInt\fP & _int)"

.PP
copy assigent operator\&. 
.PP
\fBParameters\fP
.RS 4
\fI_int\fP value to set\&. 
.RE
.PP
\fBReturns\fP
.RS 4
const \fBFDTInt\fP& 
.RE
.PP

.SS "const \fBFDTInt\fP & FDTInt::operator= (\fBFDTInt\fP && _intR)"

.PP
move assignment operator\&. 
.PP
\fBParameters\fP
.RS 4
\fI_intR\fP right value to set\&. 
.RE
.PP
\fBReturns\fP
.RS 4
const \fBFDTInt\fP& 
.RE
.PP

.SS "void FDTInt::setData (const \fBFDTInt\fP & dat)"

.PP
Set the Data of object\&. 
.PP
\fBParameters\fP
.RS 4
\fIdat\fP a \fBFDTInt\fP instance\&. 
.RE
.PP
\fBSee also\fP
.RS 4
\fBFDTInt\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "int FDTInt::data\fC [protected]\fP"

.PP
data if this \fBFDTInt\fP instance\&. 
.PP
Definition at line \fB147\fP of file \fBFDTDataType\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Freecraft from the source code\&.
