.TH "gamesave" 3 "Wed Jan 25 2023" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gamesave
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gamesave\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfcGamesaveMode\fP \fBfilemode\fP"
.br
.ti -1c
.RI "std::filesystem::path \fBworldInfoFile\fP"
.br
.ti -1c
.RI "std::filesystem::path \fBplayerDataDirectory\fP"
.br
.ti -1c
.RI "std::filesystem::path \fBchunksFilesDirectory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB26\fP of file \fBgamesave\&.hpp\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "std::filesystem::path gamesave::chunksFilesDirectory"

.PP
Definition at line \fB31\fP of file \fBgamesave\&.hpp\fP\&.
.SS "\fBfcGamesaveMode\fP gamesave::filemode"

.PP
Definition at line \fB28\fP of file \fBgamesave\&.hpp\fP\&.
.SS "std::filesystem::path gamesave::playerDataDirectory"

.PP
Definition at line \fB30\fP of file \fBgamesave\&.hpp\fP\&.
.SS "std::filesystem::path gamesave::worldInfoFile"

.PP
Definition at line \fB29\fP of file \fBgamesave\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Freecraft from the source code\&.
