.TH "src/data/item/item.hpp" 3 "Wed Jan 25 2023" "Version 00.01a07-dbg" "Freecraft" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/data/item/item.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'json/json\&.h'\fP
.br
\fC#include 'glad/glad\&.h'\fP
.br
\fC#include 'GLFW/glfw3\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include '\&.\&./uuid/uuid\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBfcitem\fP"
.br
.RI "defines item\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Freecraft from the source code\&.
