glad.c
typedef void *APIENTRYP PFNGLXGETPROCADDRESSPROC_PRIVATE(const char *)(const char *)
void* libGL
Referenced by close_gl, get_proc, open_gl.
PFNGLXGETPROCADDRESSPROC_PRIVATE gladGetProcAddressPtr
Referenced by get_proc, open_gl.
struct gladGLversionStruct GLVersion
Referenced by find_coreGL, gladLoadGLLoader.
int max_loaded_major
Referenced by find_coreGL, get_exts, has_ext.
int max_loaded_minor
Referenced by find_coreGL.
const char* exts
Referenced by get_exts, has_ext.
int num_exts_i
Referenced by free_exts, get_exts, has_ext.
char** exts_i
Referenced by free_exts, get_exts, has_ext.
int GLAD_GL_VERSION_1_0
Referenced by find_coreGL, load_GL_VERSION_1_0.
int GLAD_GL_VERSION_1_1
Referenced by find_coreGL, load_GL_VERSION_1_1.
int GLAD_GL_VERSION_1_2
Referenced by find_coreGL, load_GL_VERSION_1_2.
int GLAD_GL_VERSION_1_3
Referenced by find_coreGL, load_GL_VERSION_1_3.
int GLAD_GL_VERSION_1_4
Referenced by find_coreGL, load_GL_VERSION_1_4.
int GLAD_GL_VERSION_1_5
Referenced by find_coreGL, load_GL_VERSION_1_5.
int GLAD_GL_VERSION_2_0
Referenced by find_coreGL, load_GL_VERSION_2_0.
int GLAD_GL_VERSION_2_1
Referenced by find_coreGL, load_GL_VERSION_2_1.
int GLAD_GL_VERSION_3_0
Referenced by find_coreGL, load_GL_VERSION_3_0.
int GLAD_GL_VERSION_3_1
Referenced by find_coreGL, load_GL_VERSION_3_1.
int GLAD_GL_VERSION_3_2
Referenced by find_coreGL, load_GL_VERSION_3_2.
int GLAD_GL_VERSION_3_3
Referenced by find_coreGL, load_GL_VERSION_3_3.
int GLAD_GL_VERSION_4_0
Referenced by find_coreGL, load_GL_VERSION_4_0.
int GLAD_GL_VERSION_4_1
Referenced by find_coreGL, load_GL_VERSION_4_1.
int GLAD_GL_VERSION_4_2
Referenced by find_coreGL, load_GL_VERSION_4_2.
int GLAD_GL_VERSION_4_3
Referenced by find_coreGL, load_GL_VERSION_4_3.
int GLAD_GL_VERSION_4_4
Referenced by find_coreGL, load_GL_VERSION_4_4.
int GLAD_GL_VERSION_4_5
Referenced by find_coreGL, load_GL_VERSION_4_5.
PFNGLACCUMPROC glad_glAccum
Referenced by load_GL_VERSION_1_0.
PFNGLACTIVESHADERPROGRAMPROC glad_glActiveShaderProgram
Referenced by load_GL_VERSION_4_1.
PFNGLACTIVETEXTUREPROC glad_glActiveTexture
Referenced by load_GL_VERSION_1_3.
PFNGLALPHAFUNCPROC glad_glAlphaFunc
Referenced by load_GL_VERSION_1_0.
PFNGLARETEXTURESRESIDENTPROC glad_glAreTexturesResident
Referenced by load_GL_VERSION_1_1.
PFNGLARRAYELEMENTPROC glad_glArrayElement
Referenced by load_GL_VERSION_1_1.
PFNGLATTACHSHADERPROC glad_glAttachShader
Referenced by load_GL_VERSION_2_0.
PFNGLBEGINPROC glad_glBegin
Referenced by load_GL_VERSION_1_0.
PFNGLBEGINCONDITIONALRENDERPROC glad_glBeginConditionalRender
Referenced by load_GL_VERSION_3_0.
PFNGLBEGINQUERYPROC glad_glBeginQuery
Referenced by load_GL_VERSION_1_5.
PFNGLBEGINQUERYINDEXEDPROC glad_glBeginQueryIndexed
Referenced by load_GL_VERSION_4_0.
PFNGLBEGINTRANSFORMFEEDBACKPROC glad_glBeginTransformFeedback
Referenced by load_GL_VERSION_3_0.
PFNGLBINDATTRIBLOCATIONPROC glad_glBindAttribLocation
Referenced by load_GL_VERSION_2_0.
PFNGLBINDBUFFERPROC glad_glBindBuffer
Referenced by load_GL_VERSION_1_5.
PFNGLBINDBUFFERBASEPROC glad_glBindBufferBase
Referenced by load_GL_VERSION_3_0, load_GL_VERSION_3_1.
PFNGLBINDBUFFERRANGEPROC glad_glBindBufferRange
Referenced by load_GL_VERSION_3_0, load_GL_VERSION_3_1.
PFNGLBINDBUFFERSBASEPROC glad_glBindBuffersBase
Referenced by load_GL_VERSION_4_4.
PFNGLBINDBUFFERSRANGEPROC glad_glBindBuffersRange
Referenced by load_GL_VERSION_4_4.
PFNGLBINDFRAGDATALOCATIONPROC glad_glBindFragDataLocation
Referenced by load_GL_VERSION_3_0.
PFNGLBINDFRAGDATALOCATIONINDEXEDPROC glad_glBindFragDataLocationIndexed
Referenced by load_GL_VERSION_3_3.
PFNGLBINDFRAMEBUFFERPROC glad_glBindFramebuffer
Referenced by load_GL_VERSION_3_0.
PFNGLBINDIMAGETEXTUREPROC glad_glBindImageTexture
Referenced by load_GL_VERSION_4_2.
PFNGLBINDIMAGETEXTURESPROC glad_glBindImageTextures
Referenced by load_GL_VERSION_4_4.
PFNGLBINDPROGRAMPIPELINEPROC glad_glBindProgramPipeline
Referenced by load_GL_VERSION_4_1.
PFNGLBINDRENDERBUFFERPROC glad_glBindRenderbuffer
Referenced by load_GL_VERSION_3_0.
PFNGLBINDSAMPLERPROC glad_glBindSampler
Referenced by load_GL_VERSION_3_3.
PFNGLBINDSAMPLERSPROC glad_glBindSamplers
Referenced by load_GL_VERSION_4_4.
PFNGLBINDTEXTUREPROC glad_glBindTexture
Referenced by load_GL_VERSION_1_1.
PFNGLBINDTEXTUREUNITPROC glad_glBindTextureUnit
Referenced by load_GL_VERSION_4_5.
PFNGLBINDTEXTURESPROC glad_glBindTextures
Referenced by load_GL_VERSION_4_4.
PFNGLBINDTRANSFORMFEEDBACKPROC glad_glBindTransformFeedback
Referenced by load_GL_VERSION_4_0.
PFNGLBINDVERTEXARRAYPROC glad_glBindVertexArray
Referenced by load_GL_VERSION_3_0.
PFNGLBINDVERTEXBUFFERPROC glad_glBindVertexBuffer
Referenced by load_GL_VERSION_4_3.
PFNGLBINDVERTEXBUFFERSPROC glad_glBindVertexBuffers
Referenced by load_GL_VERSION_4_4.
PFNGLBITMAPPROC glad_glBitmap
Referenced by load_GL_VERSION_1_0.
PFNGLBLENDCOLORPROC glad_glBlendColor
Referenced by load_GL_VERSION_1_4.
PFNGLBLENDEQUATIONPROC glad_glBlendEquation
Referenced by load_GL_VERSION_1_4.
PFNGLBLENDEQUATIONSEPARATEPROC glad_glBlendEquationSeparate
Referenced by load_GL_VERSION_2_0.
PFNGLBLENDEQUATIONSEPARATEIPROC glad_glBlendEquationSeparatei
Referenced by load_GL_VERSION_4_0.
PFNGLBLENDEQUATIONIPROC glad_glBlendEquationi
Referenced by load_GL_VERSION_4_0.
PFNGLBLENDFUNCPROC glad_glBlendFunc
Referenced by load_GL_VERSION_1_0.
PFNGLBLENDFUNCSEPARATEPROC glad_glBlendFuncSeparate
Referenced by load_GL_VERSION_1_4.
PFNGLBLENDFUNCSEPARATEIPROC glad_glBlendFuncSeparatei
Referenced by load_GL_VERSION_4_0.
PFNGLBLENDFUNCIPROC glad_glBlendFunci
Referenced by load_GL_VERSION_4_0.
PFNGLBLITFRAMEBUFFERPROC glad_glBlitFramebuffer
Referenced by load_GL_VERSION_3_0.
PFNGLBLITNAMEDFRAMEBUFFERPROC glad_glBlitNamedFramebuffer
Referenced by load_GL_VERSION_4_5.
PFNGLBUFFERDATAPROC glad_glBufferData
Referenced by load_GL_VERSION_1_5.
PFNGLBUFFERSTORAGEPROC glad_glBufferStorage
Referenced by load_GL_VERSION_4_4.
PFNGLBUFFERSUBDATAPROC glad_glBufferSubData
Referenced by load_GL_VERSION_1_5.
PFNGLCALLLISTPROC glad_glCallList
Referenced by load_GL_VERSION_1_0.
PFNGLCALLLISTSPROC glad_glCallLists
Referenced by load_GL_VERSION_1_0.
PFNGLCHECKFRAMEBUFFERSTATUSPROC glad_glCheckFramebufferStatus
Referenced by load_GL_VERSION_3_0.
PFNGLCHECKNAMEDFRAMEBUFFERSTATUSPROC glad_glCheckNamedFramebufferStatus
Referenced by load_GL_VERSION_4_5.
PFNGLCLAMPCOLORPROC glad_glClampColor
Referenced by load_GL_VERSION_3_0.
PFNGLCLEARPROC glad_glClear
Referenced by load_GL_VERSION_1_0.
PFNGLCLEARACCUMPROC glad_glClearAccum
Referenced by load_GL_VERSION_1_0.
PFNGLCLEARBUFFERDATAPROC glad_glClearBufferData
Referenced by load_GL_VERSION_4_3.
PFNGLCLEARBUFFERSUBDATAPROC glad_glClearBufferSubData
Referenced by load_GL_VERSION_4_3.
PFNGLCLEARBUFFERFIPROC glad_glClearBufferfi
Referenced by load_GL_VERSION_3_0.
PFNGLCLEARBUFFERFVPROC glad_glClearBufferfv
Referenced by load_GL_VERSION_3_0.
PFNGLCLEARBUFFERIVPROC glad_glClearBufferiv
Referenced by load_GL_VERSION_3_0.
PFNGLCLEARBUFFERUIVPROC glad_glClearBufferuiv
Referenced by load_GL_VERSION_3_0.
PFNGLCLEARCOLORPROC glad_glClearColor
Referenced by load_GL_VERSION_1_0.
PFNGLCLEARDEPTHPROC glad_glClearDepth
Referenced by load_GL_VERSION_1_0.
PFNGLCLEARDEPTHFPROC glad_glClearDepthf
Referenced by load_GL_VERSION_4_1.
PFNGLCLEARINDEXPROC glad_glClearIndex
Referenced by load_GL_VERSION_1_0.
PFNGLCLEARNAMEDBUFFERDATAPROC glad_glClearNamedBufferData
Referenced by load_GL_VERSION_4_5.
PFNGLCLEARNAMEDBUFFERSUBDATAPROC glad_glClearNamedBufferSubData
Referenced by load_GL_VERSION_4_5.
PFNGLCLEARNAMEDFRAMEBUFFERFIPROC glad_glClearNamedFramebufferfi
Referenced by load_GL_VERSION_4_5.
PFNGLCLEARNAMEDFRAMEBUFFERFVPROC glad_glClearNamedFramebufferfv
Referenced by load_GL_VERSION_4_5.
PFNGLCLEARNAMEDFRAMEBUFFERIVPROC glad_glClearNamedFramebufferiv
Referenced by load_GL_VERSION_4_5.
PFNGLCLEARNAMEDFRAMEBUFFERUIVPROC glad_glClearNamedFramebufferuiv
Referenced by load_GL_VERSION_4_5.
PFNGLCLEARSTENCILPROC glad_glClearStencil
Referenced by load_GL_VERSION_1_0.
PFNGLCLEARTEXIMAGEPROC glad_glClearTexImage
Referenced by load_GL_VERSION_4_4.
PFNGLCLEARTEXSUBIMAGEPROC glad_glClearTexSubImage
Referenced by load_GL_VERSION_4_4.
PFNGLCLIENTACTIVETEXTUREPROC glad_glClientActiveTexture
Referenced by load_GL_VERSION_1_3.
PFNGLCLIENTWAITSYNCPROC glad_glClientWaitSync
Referenced by load_GL_VERSION_3_2.
PFNGLCLIPCONTROLPROC glad_glClipControl
Referenced by load_GL_VERSION_4_5.
PFNGLCLIPPLANEPROC glad_glClipPlane
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR3BPROC glad_glColor3b
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR3BVPROC glad_glColor3bv
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR3DPROC glad_glColor3d
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR3DVPROC glad_glColor3dv
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR3FPROC glad_glColor3f
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR3FVPROC glad_glColor3fv
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR3IPROC glad_glColor3i
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR3IVPROC glad_glColor3iv
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR3SPROC glad_glColor3s
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR3SVPROC glad_glColor3sv
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR3UBPROC glad_glColor3ub
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR3UBVPROC glad_glColor3ubv
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR3UIPROC glad_glColor3ui
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR3UIVPROC glad_glColor3uiv
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR3USPROC glad_glColor3us
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR3USVPROC glad_glColor3usv
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR4BPROC glad_glColor4b
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR4BVPROC glad_glColor4bv
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR4DPROC glad_glColor4d
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR4DVPROC glad_glColor4dv
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR4FPROC glad_glColor4f
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR4FVPROC glad_glColor4fv
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR4IPROC glad_glColor4i
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR4IVPROC glad_glColor4iv
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR4SPROC glad_glColor4s
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR4SVPROC glad_glColor4sv
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR4UBPROC glad_glColor4ub
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR4UBVPROC glad_glColor4ubv
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR4UIPROC glad_glColor4ui
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR4UIVPROC glad_glColor4uiv
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR4USPROC glad_glColor4us
Referenced by load_GL_VERSION_1_0.
PFNGLCOLOR4USVPROC glad_glColor4usv
Referenced by load_GL_VERSION_1_0.
PFNGLCOLORMASKPROC glad_glColorMask
Referenced by load_GL_VERSION_1_0.
PFNGLCOLORMASKIPROC glad_glColorMaski
Referenced by load_GL_VERSION_3_0.
PFNGLCOLORMATERIALPROC glad_glColorMaterial
Referenced by load_GL_VERSION_1_0.
PFNGLCOLORP3UIPROC glad_glColorP3ui
Referenced by load_GL_VERSION_3_3.
PFNGLCOLORP3UIVPROC glad_glColorP3uiv
Referenced by load_GL_VERSION_3_3.
PFNGLCOLORP4UIPROC glad_glColorP4ui
Referenced by load_GL_VERSION_3_3.
PFNGLCOLORP4UIVPROC glad_glColorP4uiv
Referenced by load_GL_VERSION_3_3.
PFNGLCOLORPOINTERPROC glad_glColorPointer
Referenced by load_GL_VERSION_1_1.
PFNGLCOMPILESHADERPROC glad_glCompileShader
Referenced by load_GL_VERSION_2_0.
PFNGLCOMPRESSEDTEXIMAGE1DPROC glad_glCompressedTexImage1D
Referenced by load_GL_VERSION_1_3.
PFNGLCOMPRESSEDTEXIMAGE2DPROC glad_glCompressedTexImage2D
Referenced by load_GL_VERSION_1_3.
PFNGLCOMPRESSEDTEXIMAGE3DPROC glad_glCompressedTexImage3D
Referenced by load_GL_VERSION_1_3.
PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC glad_glCompressedTexSubImage1D
Referenced by load_GL_VERSION_1_3.
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glad_glCompressedTexSubImage2D
Referenced by load_GL_VERSION_1_3.
PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC glad_glCompressedTexSubImage3D
Referenced by load_GL_VERSION_1_3.
PFNGLCOMPRESSEDTEXTURESUBIMAGE1DPROC glad_glCompressedTextureSubImage1D
Referenced by load_GL_VERSION_4_5.
PFNGLCOMPRESSEDTEXTURESUBIMAGE2DPROC glad_glCompressedTextureSubImage2D
Referenced by load_GL_VERSION_4_5.
PFNGLCOMPRESSEDTEXTURESUBIMAGE3DPROC glad_glCompressedTextureSubImage3D
Referenced by load_GL_VERSION_4_5.
PFNGLCOPYBUFFERSUBDATAPROC glad_glCopyBufferSubData
Referenced by load_GL_VERSION_3_1.
PFNGLCOPYIMAGESUBDATAPROC glad_glCopyImageSubData
Referenced by load_GL_VERSION_4_3.
PFNGLCOPYNAMEDBUFFERSUBDATAPROC glad_glCopyNamedBufferSubData
Referenced by load_GL_VERSION_4_5.
PFNGLCOPYPIXELSPROC glad_glCopyPixels
Referenced by load_GL_VERSION_1_0.
PFNGLCOPYTEXIMAGE1DPROC glad_glCopyTexImage1D
Referenced by load_GL_VERSION_1_1.
PFNGLCOPYTEXIMAGE2DPROC glad_glCopyTexImage2D
Referenced by load_GL_VERSION_1_1.
PFNGLCOPYTEXSUBIMAGE1DPROC glad_glCopyTexSubImage1D
Referenced by load_GL_VERSION_1_1.
PFNGLCOPYTEXSUBIMAGE2DPROC glad_glCopyTexSubImage2D
Referenced by load_GL_VERSION_1_1.
PFNGLCOPYTEXSUBIMAGE3DPROC glad_glCopyTexSubImage3D
Referenced by load_GL_VERSION_1_2.
PFNGLCOPYTEXTURESUBIMAGE1DPROC glad_glCopyTextureSubImage1D
Referenced by load_GL_VERSION_4_5.
PFNGLCOPYTEXTURESUBIMAGE2DPROC glad_glCopyTextureSubImage2D
Referenced by load_GL_VERSION_4_5.
PFNGLCOPYTEXTURESUBIMAGE3DPROC glad_glCopyTextureSubImage3D
Referenced by load_GL_VERSION_4_5.
PFNGLCREATEBUFFERSPROC glad_glCreateBuffers
Referenced by load_GL_VERSION_4_5.
PFNGLCREATEFRAMEBUFFERSPROC glad_glCreateFramebuffers
Referenced by load_GL_VERSION_4_5.
PFNGLCREATEPROGRAMPROC glad_glCreateProgram
Referenced by load_GL_VERSION_2_0.
PFNGLCREATEPROGRAMPIPELINESPROC glad_glCreateProgramPipelines
Referenced by load_GL_VERSION_4_5.
PFNGLCREATEQUERIESPROC glad_glCreateQueries
Referenced by load_GL_VERSION_4_5.
PFNGLCREATERENDERBUFFERSPROC glad_glCreateRenderbuffers
Referenced by load_GL_VERSION_4_5.
PFNGLCREATESAMPLERSPROC glad_glCreateSamplers
Referenced by load_GL_VERSION_4_5.
PFNGLCREATESHADERPROC glad_glCreateShader
Referenced by load_GL_VERSION_2_0.
PFNGLCREATESHADERPROGRAMVPROC glad_glCreateShaderProgramv
Referenced by load_GL_VERSION_4_1.
PFNGLCREATETEXTURESPROC glad_glCreateTextures
Referenced by load_GL_VERSION_4_5.
PFNGLCREATETRANSFORMFEEDBACKSPROC glad_glCreateTransformFeedbacks
Referenced by load_GL_VERSION_4_5.
PFNGLCREATEVERTEXARRAYSPROC glad_glCreateVertexArrays
Referenced by load_GL_VERSION_4_5.
PFNGLCULLFACEPROC glad_glCullFace
Referenced by load_GL_VERSION_1_0.
PFNGLDEBUGMESSAGECALLBACKPROC glad_glDebugMessageCallback
Referenced by load_GL_VERSION_4_3.
PFNGLDEBUGMESSAGECONTROLPROC glad_glDebugMessageControl
Referenced by load_GL_VERSION_4_3.
PFNGLDEBUGMESSAGEINSERTPROC glad_glDebugMessageInsert
Referenced by load_GL_VERSION_4_3.
PFNGLDELETEBUFFERSPROC glad_glDeleteBuffers
Referenced by load_GL_VERSION_1_5.
PFNGLDELETEFRAMEBUFFERSPROC glad_glDeleteFramebuffers
Referenced by load_GL_VERSION_3_0.
PFNGLDELETELISTSPROC glad_glDeleteLists
Referenced by load_GL_VERSION_1_0.
PFNGLDELETEPROGRAMPROC glad_glDeleteProgram
Referenced by load_GL_VERSION_2_0.
PFNGLDELETEPROGRAMPIPELINESPROC glad_glDeleteProgramPipelines
Referenced by load_GL_VERSION_4_1.
PFNGLDELETEQUERIESPROC glad_glDeleteQueries
Referenced by load_GL_VERSION_1_5.
PFNGLDELETERENDERBUFFERSPROC glad_glDeleteRenderbuffers
Referenced by load_GL_VERSION_3_0.
PFNGLDELETESAMPLERSPROC glad_glDeleteSamplers
Referenced by load_GL_VERSION_3_3.
PFNGLDELETESHADERPROC glad_glDeleteShader
Referenced by load_GL_VERSION_2_0.
PFNGLDELETESYNCPROC glad_glDeleteSync
Referenced by load_GL_VERSION_3_2.
PFNGLDELETETEXTURESPROC glad_glDeleteTextures
Referenced by load_GL_VERSION_1_1.
PFNGLDELETETRANSFORMFEEDBACKSPROC glad_glDeleteTransformFeedbacks
Referenced by load_GL_VERSION_4_0.
PFNGLDELETEVERTEXARRAYSPROC glad_glDeleteVertexArrays
Referenced by load_GL_VERSION_3_0.
PFNGLDEPTHFUNCPROC glad_glDepthFunc
Referenced by load_GL_VERSION_1_0.
PFNGLDEPTHMASKPROC glad_glDepthMask
Referenced by load_GL_VERSION_1_0.
PFNGLDEPTHRANGEPROC glad_glDepthRange
Referenced by load_GL_VERSION_1_0.
PFNGLDEPTHRANGEARRAYVPROC glad_glDepthRangeArrayv
Referenced by load_GL_VERSION_4_1.
PFNGLDEPTHRANGEINDEXEDPROC glad_glDepthRangeIndexed
Referenced by load_GL_VERSION_4_1.
PFNGLDEPTHRANGEFPROC glad_glDepthRangef
Referenced by load_GL_VERSION_4_1.
PFNGLDETACHSHADERPROC glad_glDetachShader
Referenced by load_GL_VERSION_2_0.
PFNGLDISABLEPROC glad_glDisable
Referenced by load_GL_VERSION_1_0.
PFNGLDISABLECLIENTSTATEPROC glad_glDisableClientState
Referenced by load_GL_VERSION_1_1.
PFNGLDISABLEVERTEXARRAYATTRIBPROC glad_glDisableVertexArrayAttrib
Referenced by load_GL_VERSION_4_5.
PFNGLDISABLEVERTEXATTRIBARRAYPROC glad_glDisableVertexAttribArray
Referenced by load_GL_VERSION_2_0.
PFNGLDISABLEIPROC glad_glDisablei
Referenced by load_GL_VERSION_3_0.
PFNGLDISPATCHCOMPUTEPROC glad_glDispatchCompute
Referenced by load_GL_VERSION_4_3.
PFNGLDISPATCHCOMPUTEINDIRECTPROC glad_glDispatchComputeIndirect
Referenced by load_GL_VERSION_4_3.
PFNGLDRAWARRAYSPROC glad_glDrawArrays
Referenced by load_GL_VERSION_1_1.
PFNGLDRAWARRAYSINDIRECTPROC glad_glDrawArraysIndirect
Referenced by load_GL_VERSION_4_0.
PFNGLDRAWARRAYSINSTANCEDPROC glad_glDrawArraysInstanced
Referenced by load_GL_VERSION_3_1.
PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC glad_glDrawArraysInstancedBaseInstance
Referenced by load_GL_VERSION_4_2.
PFNGLDRAWBUFFERPROC glad_glDrawBuffer
Referenced by load_GL_VERSION_1_0.
PFNGLDRAWBUFFERSPROC glad_glDrawBuffers
Referenced by load_GL_VERSION_2_0.
PFNGLDRAWELEMENTSPROC glad_glDrawElements
Referenced by load_GL_VERSION_1_1.
PFNGLDRAWELEMENTSBASEVERTEXPROC glad_glDrawElementsBaseVertex
Referenced by load_GL_VERSION_3_2.
PFNGLDRAWELEMENTSINDIRECTPROC glad_glDrawElementsIndirect
Referenced by load_GL_VERSION_4_0.
PFNGLDRAWELEMENTSINSTANCEDPROC glad_glDrawElementsInstanced
Referenced by load_GL_VERSION_3_1.
PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC glad_glDrawElementsInstancedBaseInstance
Referenced by load_GL_VERSION_4_2.
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC glad_glDrawElementsInstancedBaseVertex
Referenced by load_GL_VERSION_3_2.
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC glad_glDrawElementsInstancedBaseVertexBaseInstance
Referenced by load_GL_VERSION_4_2.
PFNGLDRAWPIXELSPROC glad_glDrawPixels
Referenced by load_GL_VERSION_1_0.
PFNGLDRAWRANGEELEMENTSPROC glad_glDrawRangeElements
Referenced by load_GL_VERSION_1_2.
PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC glad_glDrawRangeElementsBaseVertex
Referenced by load_GL_VERSION_3_2.
PFNGLDRAWTRANSFORMFEEDBACKPROC glad_glDrawTransformFeedback
Referenced by load_GL_VERSION_4_0.
PFNGLDRAWTRANSFORMFEEDBACKINSTANCEDPROC glad_glDrawTransformFeedbackInstanced
Referenced by load_GL_VERSION_4_2.
PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC glad_glDrawTransformFeedbackStream
Referenced by load_GL_VERSION_4_0.
PFNGLDRAWTRANSFORMFEEDBACKSTREAMINSTANCEDPROC glad_glDrawTransformFeedbackStreamInstanced
Referenced by load_GL_VERSION_4_2.
PFNGLEDGEFLAGPROC glad_glEdgeFlag
Referenced by load_GL_VERSION_1_0.
PFNGLEDGEFLAGPOINTERPROC glad_glEdgeFlagPointer
Referenced by load_GL_VERSION_1_1.
PFNGLEDGEFLAGVPROC glad_glEdgeFlagv
Referenced by load_GL_VERSION_1_0.
PFNGLENABLEPROC glad_glEnable
Referenced by load_GL_VERSION_1_0.
PFNGLENABLECLIENTSTATEPROC glad_glEnableClientState
Referenced by load_GL_VERSION_1_1.
PFNGLENABLEVERTEXARRAYATTRIBPROC glad_glEnableVertexArrayAttrib
Referenced by load_GL_VERSION_4_5.
PFNGLENABLEVERTEXATTRIBARRAYPROC glad_glEnableVertexAttribArray
Referenced by load_GL_VERSION_2_0.
PFNGLENABLEIPROC glad_glEnablei
Referenced by load_GL_VERSION_3_0.
PFNGLENDPROC glad_glEnd
Referenced by load_GL_VERSION_1_0.
PFNGLENDCONDITIONALRENDERPROC glad_glEndConditionalRender
Referenced by load_GL_VERSION_3_0.
PFNGLENDLISTPROC glad_glEndList
Referenced by load_GL_VERSION_1_0.
PFNGLENDQUERYPROC glad_glEndQuery
Referenced by load_GL_VERSION_1_5.
PFNGLENDQUERYINDEXEDPROC glad_glEndQueryIndexed
Referenced by load_GL_VERSION_4_0.
PFNGLENDTRANSFORMFEEDBACKPROC glad_glEndTransformFeedback
Referenced by load_GL_VERSION_3_0.
PFNGLEVALCOORD1DPROC glad_glEvalCoord1d
Referenced by load_GL_VERSION_1_0.
PFNGLEVALCOORD1DVPROC glad_glEvalCoord1dv
Referenced by load_GL_VERSION_1_0.
PFNGLEVALCOORD1FPROC glad_glEvalCoord1f
Referenced by load_GL_VERSION_1_0.
PFNGLEVALCOORD1FVPROC glad_glEvalCoord1fv
Referenced by load_GL_VERSION_1_0.
PFNGLEVALCOORD2DPROC glad_glEvalCoord2d
Referenced by load_GL_VERSION_1_0.
PFNGLEVALCOORD2DVPROC glad_glEvalCoord2dv
Referenced by load_GL_VERSION_1_0.
PFNGLEVALCOORD2FPROC glad_glEvalCoord2f
Referenced by load_GL_VERSION_1_0.
PFNGLEVALCOORD2FVPROC glad_glEvalCoord2fv
Referenced by load_GL_VERSION_1_0.
PFNGLEVALMESH1PROC glad_glEvalMesh1
Referenced by load_GL_VERSION_1_0.
PFNGLEVALMESH2PROC glad_glEvalMesh2
Referenced by load_GL_VERSION_1_0.
PFNGLEVALPOINT1PROC glad_glEvalPoint1
Referenced by load_GL_VERSION_1_0.
PFNGLEVALPOINT2PROC glad_glEvalPoint2
Referenced by load_GL_VERSION_1_0.
PFNGLFEEDBACKBUFFERPROC glad_glFeedbackBuffer
Referenced by load_GL_VERSION_1_0.
PFNGLFENCESYNCPROC glad_glFenceSync
Referenced by load_GL_VERSION_3_2.
PFNGLFINISHPROC glad_glFinish
Referenced by load_GL_VERSION_1_0.
PFNGLFLUSHPROC glad_glFlush
Referenced by load_GL_VERSION_1_0.
PFNGLFLUSHMAPPEDBUFFERRANGEPROC glad_glFlushMappedBufferRange
Referenced by load_GL_VERSION_3_0.
PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC glad_glFlushMappedNamedBufferRange
Referenced by load_GL_VERSION_4_5.
PFNGLFOGCOORDPOINTERPROC glad_glFogCoordPointer
Referenced by load_GL_VERSION_1_4.
PFNGLFOGCOORDDPROC glad_glFogCoordd
Referenced by load_GL_VERSION_1_4.
PFNGLFOGCOORDDVPROC glad_glFogCoorddv
Referenced by load_GL_VERSION_1_4.
PFNGLFOGCOORDFPROC glad_glFogCoordf
Referenced by load_GL_VERSION_1_4.
PFNGLFOGCOORDFVPROC glad_glFogCoordfv
Referenced by load_GL_VERSION_1_4.
PFNGLFOGFPROC glad_glFogf
Referenced by load_GL_VERSION_1_0.
PFNGLFOGFVPROC glad_glFogfv
Referenced by load_GL_VERSION_1_0.
PFNGLFOGIPROC glad_glFogi
Referenced by load_GL_VERSION_1_0.
PFNGLFOGIVPROC glad_glFogiv
Referenced by load_GL_VERSION_1_0.
PFNGLFRAMEBUFFERPARAMETERIPROC glad_glFramebufferParameteri
Referenced by load_GL_VERSION_4_3.
PFNGLFRAMEBUFFERRENDERBUFFERPROC glad_glFramebufferRenderbuffer
Referenced by load_GL_VERSION_3_0.
PFNGLFRAMEBUFFERTEXTUREPROC glad_glFramebufferTexture
Referenced by load_GL_VERSION_3_2.
PFNGLFRAMEBUFFERTEXTURE1DPROC glad_glFramebufferTexture1D
Referenced by load_GL_VERSION_3_0.
PFNGLFRAMEBUFFERTEXTURE2DPROC glad_glFramebufferTexture2D
Referenced by load_GL_VERSION_3_0.
PFNGLFRAMEBUFFERTEXTURE3DPROC glad_glFramebufferTexture3D
Referenced by load_GL_VERSION_3_0.
PFNGLFRAMEBUFFERTEXTURELAYERPROC glad_glFramebufferTextureLayer
Referenced by load_GL_VERSION_3_0.
PFNGLFRONTFACEPROC glad_glFrontFace
Referenced by load_GL_VERSION_1_0.
PFNGLFRUSTUMPROC glad_glFrustum
Referenced by load_GL_VERSION_1_0.
PFNGLGENBUFFERSPROC glad_glGenBuffers
Referenced by load_GL_VERSION_1_5.
PFNGLGENFRAMEBUFFERSPROC glad_glGenFramebuffers
Referenced by load_GL_VERSION_3_0.
PFNGLGENLISTSPROC glad_glGenLists
Referenced by load_GL_VERSION_1_0.
PFNGLGENPROGRAMPIPELINESPROC glad_glGenProgramPipelines
Referenced by load_GL_VERSION_4_1.
PFNGLGENQUERIESPROC glad_glGenQueries
Referenced by load_GL_VERSION_1_5.
PFNGLGENRENDERBUFFERSPROC glad_glGenRenderbuffers
Referenced by load_GL_VERSION_3_0.
PFNGLGENSAMPLERSPROC glad_glGenSamplers
Referenced by load_GL_VERSION_3_3.
PFNGLGENTEXTURESPROC glad_glGenTextures
Referenced by load_GL_VERSION_1_1.
PFNGLGENTRANSFORMFEEDBACKSPROC glad_glGenTransformFeedbacks
Referenced by load_GL_VERSION_4_0.
PFNGLGENVERTEXARRAYSPROC glad_glGenVertexArrays
Referenced by load_GL_VERSION_3_0.
PFNGLGENERATEMIPMAPPROC glad_glGenerateMipmap
Referenced by load_GL_VERSION_3_0.
PFNGLGENERATETEXTUREMIPMAPPROC glad_glGenerateTextureMipmap
Referenced by load_GL_VERSION_4_5.
PFNGLGETACTIVEATOMICCOUNTERBUFFERIVPROC glad_glGetActiveAtomicCounterBufferiv
Referenced by load_GL_VERSION_4_2.
PFNGLGETACTIVEATTRIBPROC glad_glGetActiveAttrib
Referenced by load_GL_VERSION_2_0.
PFNGLGETACTIVESUBROUTINENAMEPROC glad_glGetActiveSubroutineName
Referenced by load_GL_VERSION_4_0.
PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC glad_glGetActiveSubroutineUniformName
Referenced by load_GL_VERSION_4_0.
PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC glad_glGetActiveSubroutineUniformiv
Referenced by load_GL_VERSION_4_0.
PFNGLGETACTIVEUNIFORMPROC glad_glGetActiveUniform
Referenced by load_GL_VERSION_2_0.
PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC glad_glGetActiveUniformBlockName
Referenced by load_GL_VERSION_3_1.
PFNGLGETACTIVEUNIFORMBLOCKIVPROC glad_glGetActiveUniformBlockiv
Referenced by load_GL_VERSION_3_1.
PFNGLGETACTIVEUNIFORMNAMEPROC glad_glGetActiveUniformName
Referenced by load_GL_VERSION_3_1.
PFNGLGETACTIVEUNIFORMSIVPROC glad_glGetActiveUniformsiv
Referenced by load_GL_VERSION_3_1.
PFNGLGETATTACHEDSHADERSPROC glad_glGetAttachedShaders
Referenced by load_GL_VERSION_2_0.
PFNGLGETATTRIBLOCATIONPROC glad_glGetAttribLocation
Referenced by load_GL_VERSION_2_0.
PFNGLGETBOOLEANI_VPROC glad_glGetBooleani_v
Referenced by load_GL_VERSION_3_0.
PFNGLGETBOOLEANVPROC glad_glGetBooleanv
Referenced by load_GL_VERSION_1_0.
PFNGLGETBUFFERPARAMETERI64VPROC glad_glGetBufferParameteri64v
Referenced by load_GL_VERSION_3_2.
PFNGLGETBUFFERPARAMETERIVPROC glad_glGetBufferParameteriv
Referenced by load_GL_VERSION_1_5.
PFNGLGETBUFFERPOINTERVPROC glad_glGetBufferPointerv
Referenced by load_GL_VERSION_1_5.
PFNGLGETBUFFERSUBDATAPROC glad_glGetBufferSubData
Referenced by load_GL_VERSION_1_5.
PFNGLGETCLIPPLANEPROC glad_glGetClipPlane
Referenced by load_GL_VERSION_1_0.
PFNGLGETCOMPRESSEDTEXIMAGEPROC glad_glGetCompressedTexImage
Referenced by load_GL_VERSION_1_3.
PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC glad_glGetCompressedTextureImage
Referenced by load_GL_VERSION_4_5.
PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC glad_glGetCompressedTextureSubImage
Referenced by load_GL_VERSION_4_5.
PFNGLGETDEBUGMESSAGELOGPROC glad_glGetDebugMessageLog
Referenced by load_GL_VERSION_4_3.
PFNGLGETDOUBLEI_VPROC glad_glGetDoublei_v
Referenced by load_GL_VERSION_4_1.
PFNGLGETDOUBLEVPROC glad_glGetDoublev
Referenced by load_GL_VERSION_1_0.
PFNGLGETERRORPROC glad_glGetError
Referenced by load_GL_VERSION_1_0.
PFNGLGETFLOATI_VPROC glad_glGetFloati_v
Referenced by load_GL_VERSION_4_1.
PFNGLGETFLOATVPROC glad_glGetFloatv
Referenced by load_GL_VERSION_1_0.
PFNGLGETFRAGDATAINDEXPROC glad_glGetFragDataIndex
Referenced by load_GL_VERSION_3_3.
PFNGLGETFRAGDATALOCATIONPROC glad_glGetFragDataLocation
Referenced by load_GL_VERSION_3_0.
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glad_glGetFramebufferAttachmentParameteriv
Referenced by load_GL_VERSION_3_0.
PFNGLGETFRAMEBUFFERPARAMETERIVPROC glad_glGetFramebufferParameteriv
Referenced by load_GL_VERSION_4_3.
PFNGLGETGRAPHICSRESETSTATUSPROC glad_glGetGraphicsResetStatus
Referenced by load_GL_VERSION_4_5.
PFNGLGETINTEGER64I_VPROC glad_glGetInteger64i_v
Referenced by load_GL_VERSION_3_2.
PFNGLGETINTEGER64VPROC glad_glGetInteger64v
Referenced by load_GL_VERSION_3_2.
PFNGLGETINTEGERI_VPROC glad_glGetIntegeri_v
Referenced by load_GL_VERSION_3_0, load_GL_VERSION_3_1.
PFNGLGETINTEGERVPROC glad_glGetIntegerv
Referenced by load_GL_VERSION_1_0.
PFNGLGETINTERNALFORMATI64VPROC glad_glGetInternalformati64v
Referenced by load_GL_VERSION_4_3.
PFNGLGETINTERNALFORMATIVPROC glad_glGetInternalformativ
Referenced by load_GL_VERSION_4_2.
PFNGLGETLIGHTFVPROC glad_glGetLightfv
Referenced by load_GL_VERSION_1_0.
PFNGLGETLIGHTIVPROC glad_glGetLightiv
Referenced by load_GL_VERSION_1_0.
PFNGLGETMAPDVPROC glad_glGetMapdv
Referenced by load_GL_VERSION_1_0.
PFNGLGETMAPFVPROC glad_glGetMapfv
Referenced by load_GL_VERSION_1_0.
PFNGLGETMAPIVPROC glad_glGetMapiv
Referenced by load_GL_VERSION_1_0.
PFNGLGETMATERIALFVPROC glad_glGetMaterialfv
Referenced by load_GL_VERSION_1_0.
PFNGLGETMATERIALIVPROC glad_glGetMaterialiv
Referenced by load_GL_VERSION_1_0.
PFNGLGETMULTISAMPLEFVPROC glad_glGetMultisamplefv
Referenced by load_GL_VERSION_3_2.
PFNGLGETNAMEDBUFFERPARAMETERI64VPROC glad_glGetNamedBufferParameteri64v
Referenced by load_GL_VERSION_4_5.
PFNGLGETNAMEDBUFFERPARAMETERIVPROC glad_glGetNamedBufferParameteriv
Referenced by load_GL_VERSION_4_5.
PFNGLGETNAMEDBUFFERPOINTERVPROC glad_glGetNamedBufferPointerv
Referenced by load_GL_VERSION_4_5.
PFNGLGETNAMEDBUFFERSUBDATAPROC glad_glGetNamedBufferSubData
Referenced by load_GL_VERSION_4_5.
PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVPROC glad_glGetNamedFramebufferAttachmentParameteriv
Referenced by load_GL_VERSION_4_5.
PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVPROC glad_glGetNamedFramebufferParameteriv
Referenced by load_GL_VERSION_4_5.
PFNGLGETNAMEDRENDERBUFFERPARAMETERIVPROC glad_glGetNamedRenderbufferParameteriv
Referenced by load_GL_VERSION_4_5.
PFNGLGETOBJECTLABELPROC glad_glGetObjectLabel
Referenced by load_GL_VERSION_4_3.
PFNGLGETOBJECTPTRLABELPROC glad_glGetObjectPtrLabel
Referenced by load_GL_VERSION_4_3.
PFNGLGETPIXELMAPFVPROC glad_glGetPixelMapfv
Referenced by load_GL_VERSION_1_0.
PFNGLGETPIXELMAPUIVPROC glad_glGetPixelMapuiv
Referenced by load_GL_VERSION_1_0.
PFNGLGETPIXELMAPUSVPROC glad_glGetPixelMapusv
Referenced by load_GL_VERSION_1_0.
PFNGLGETPOINTERVPROC glad_glGetPointerv
Referenced by load_GL_VERSION_1_1, load_GL_VERSION_4_3.
PFNGLGETPOLYGONSTIPPLEPROC glad_glGetPolygonStipple
Referenced by load_GL_VERSION_1_0.
PFNGLGETPROGRAMBINARYPROC glad_glGetProgramBinary
Referenced by load_GL_VERSION_4_1.
PFNGLGETPROGRAMINFOLOGPROC glad_glGetProgramInfoLog
Referenced by load_GL_VERSION_2_0.
PFNGLGETPROGRAMINTERFACEIVPROC glad_glGetProgramInterfaceiv
Referenced by load_GL_VERSION_4_3.
PFNGLGETPROGRAMPIPELINEINFOLOGPROC glad_glGetProgramPipelineInfoLog
Referenced by load_GL_VERSION_4_1.
PFNGLGETPROGRAMPIPELINEIVPROC glad_glGetProgramPipelineiv
Referenced by load_GL_VERSION_4_1.
PFNGLGETPROGRAMRESOURCEINDEXPROC glad_glGetProgramResourceIndex
Referenced by load_GL_VERSION_4_3.
PFNGLGETPROGRAMRESOURCELOCATIONPROC glad_glGetProgramResourceLocation
Referenced by load_GL_VERSION_4_3.
PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC glad_glGetProgramResourceLocationIndex
Referenced by load_GL_VERSION_4_3.
PFNGLGETPROGRAMRESOURCENAMEPROC glad_glGetProgramResourceName
Referenced by load_GL_VERSION_4_3.
PFNGLGETPROGRAMRESOURCEIVPROC glad_glGetProgramResourceiv
Referenced by load_GL_VERSION_4_3.
PFNGLGETPROGRAMSTAGEIVPROC glad_glGetProgramStageiv
Referenced by load_GL_VERSION_4_0.
PFNGLGETPROGRAMIVPROC glad_glGetProgramiv
Referenced by load_GL_VERSION_2_0.
PFNGLGETQUERYBUFFEROBJECTI64VPROC glad_glGetQueryBufferObjecti64v
Referenced by load_GL_VERSION_4_5.
PFNGLGETQUERYBUFFEROBJECTIVPROC glad_glGetQueryBufferObjectiv
Referenced by load_GL_VERSION_4_5.
PFNGLGETQUERYBUFFEROBJECTUI64VPROC glad_glGetQueryBufferObjectui64v
Referenced by load_GL_VERSION_4_5.
PFNGLGETQUERYBUFFEROBJECTUIVPROC glad_glGetQueryBufferObjectuiv
Referenced by load_GL_VERSION_4_5.
PFNGLGETQUERYINDEXEDIVPROC glad_glGetQueryIndexediv
Referenced by load_GL_VERSION_4_0.
PFNGLGETQUERYOBJECTI64VPROC glad_glGetQueryObjecti64v
Referenced by load_GL_VERSION_3_3.
PFNGLGETQUERYOBJECTIVPROC glad_glGetQueryObjectiv
Referenced by load_GL_VERSION_1_5.
PFNGLGETQUERYOBJECTUI64VPROC glad_glGetQueryObjectui64v
Referenced by load_GL_VERSION_3_3.
PFNGLGETQUERYOBJECTUIVPROC glad_glGetQueryObjectuiv
Referenced by load_GL_VERSION_1_5.
PFNGLGETQUERYIVPROC glad_glGetQueryiv
Referenced by load_GL_VERSION_1_5.
PFNGLGETRENDERBUFFERPARAMETERIVPROC glad_glGetRenderbufferParameteriv
Referenced by load_GL_VERSION_3_0.
PFNGLGETSAMPLERPARAMETERIIVPROC glad_glGetSamplerParameterIiv
Referenced by load_GL_VERSION_3_3.
PFNGLGETSAMPLERPARAMETERIUIVPROC glad_glGetSamplerParameterIuiv
Referenced by load_GL_VERSION_3_3.
PFNGLGETSAMPLERPARAMETERFVPROC glad_glGetSamplerParameterfv
Referenced by load_GL_VERSION_3_3.
PFNGLGETSAMPLERPARAMETERIVPROC glad_glGetSamplerParameteriv
Referenced by load_GL_VERSION_3_3.
PFNGLGETSHADERINFOLOGPROC glad_glGetShaderInfoLog
Referenced by load_GL_VERSION_2_0.
PFNGLGETSHADERPRECISIONFORMATPROC glad_glGetShaderPrecisionFormat
Referenced by load_GL_VERSION_4_1.
PFNGLGETSHADERSOURCEPROC glad_glGetShaderSource
Referenced by load_GL_VERSION_2_0.
PFNGLGETSHADERIVPROC glad_glGetShaderiv
Referenced by load_GL_VERSION_2_0.
PFNGLGETSTRINGPROC glad_glGetString
Referenced by load_GL_VERSION_1_0.
PFNGLGETSTRINGIPROC glad_glGetStringi
Referenced by load_GL_VERSION_3_0.
PFNGLGETSUBROUTINEINDEXPROC glad_glGetSubroutineIndex
Referenced by load_GL_VERSION_4_0.
PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC glad_glGetSubroutineUniformLocation
Referenced by load_GL_VERSION_4_0.
PFNGLGETSYNCIVPROC glad_glGetSynciv
Referenced by load_GL_VERSION_3_2.
PFNGLGETTEXENVFVPROC glad_glGetTexEnvfv
Referenced by load_GL_VERSION_1_0.
PFNGLGETTEXENVIVPROC glad_glGetTexEnviv
Referenced by load_GL_VERSION_1_0.
PFNGLGETTEXGENDVPROC glad_glGetTexGendv
Referenced by load_GL_VERSION_1_0.
PFNGLGETTEXGENFVPROC glad_glGetTexGenfv
Referenced by load_GL_VERSION_1_0.
PFNGLGETTEXGENIVPROC glad_glGetTexGeniv
Referenced by load_GL_VERSION_1_0.
PFNGLGETTEXIMAGEPROC glad_glGetTexImage
Referenced by load_GL_VERSION_1_0.
PFNGLGETTEXLEVELPARAMETERFVPROC glad_glGetTexLevelParameterfv
Referenced by load_GL_VERSION_1_0.
PFNGLGETTEXLEVELPARAMETERIVPROC glad_glGetTexLevelParameteriv
Referenced by load_GL_VERSION_1_0.
PFNGLGETTEXPARAMETERIIVPROC glad_glGetTexParameterIiv
Referenced by load_GL_VERSION_3_0.
PFNGLGETTEXPARAMETERIUIVPROC glad_glGetTexParameterIuiv
Referenced by load_GL_VERSION_3_0.
PFNGLGETTEXPARAMETERFVPROC glad_glGetTexParameterfv
Referenced by load_GL_VERSION_1_0.
PFNGLGETTEXPARAMETERIVPROC glad_glGetTexParameteriv
Referenced by load_GL_VERSION_1_0.
PFNGLGETTEXTUREIMAGEPROC glad_glGetTextureImage
Referenced by load_GL_VERSION_4_5.
PFNGLGETTEXTURELEVELPARAMETERFVPROC glad_glGetTextureLevelParameterfv
Referenced by load_GL_VERSION_4_5.
PFNGLGETTEXTURELEVELPARAMETERIVPROC glad_glGetTextureLevelParameteriv
Referenced by load_GL_VERSION_4_5.
PFNGLGETTEXTUREPARAMETERIIVPROC glad_glGetTextureParameterIiv
Referenced by load_GL_VERSION_4_5.
PFNGLGETTEXTUREPARAMETERIUIVPROC glad_glGetTextureParameterIuiv
Referenced by load_GL_VERSION_4_5.
PFNGLGETTEXTUREPARAMETERFVPROC glad_glGetTextureParameterfv
Referenced by load_GL_VERSION_4_5.
PFNGLGETTEXTUREPARAMETERIVPROC glad_glGetTextureParameteriv
Referenced by load_GL_VERSION_4_5.
PFNGLGETTEXTURESUBIMAGEPROC glad_glGetTextureSubImage
Referenced by load_GL_VERSION_4_5.
PFNGLGETTRANSFORMFEEDBACKVARYINGPROC glad_glGetTransformFeedbackVarying
Referenced by load_GL_VERSION_3_0.
PFNGLGETTRANSFORMFEEDBACKI64_VPROC glad_glGetTransformFeedbacki64_v
Referenced by load_GL_VERSION_4_5.
PFNGLGETTRANSFORMFEEDBACKI_VPROC glad_glGetTransformFeedbacki_v
Referenced by load_GL_VERSION_4_5.
PFNGLGETTRANSFORMFEEDBACKIVPROC glad_glGetTransformFeedbackiv
Referenced by load_GL_VERSION_4_5.
PFNGLGETUNIFORMBLOCKINDEXPROC glad_glGetUniformBlockIndex
Referenced by load_GL_VERSION_3_1.
PFNGLGETUNIFORMINDICESPROC glad_glGetUniformIndices
Referenced by load_GL_VERSION_3_1.
PFNGLGETUNIFORMLOCATIONPROC glad_glGetUniformLocation
Referenced by load_GL_VERSION_2_0.
PFNGLGETUNIFORMSUBROUTINEUIVPROC glad_glGetUniformSubroutineuiv
Referenced by load_GL_VERSION_4_0.
PFNGLGETUNIFORMDVPROC glad_glGetUniformdv
Referenced by load_GL_VERSION_4_0.
PFNGLGETUNIFORMFVPROC glad_glGetUniformfv
Referenced by load_GL_VERSION_2_0.
PFNGLGETUNIFORMIVPROC glad_glGetUniformiv
Referenced by load_GL_VERSION_2_0.
PFNGLGETUNIFORMUIVPROC glad_glGetUniformuiv
Referenced by load_GL_VERSION_3_0.
PFNGLGETVERTEXARRAYINDEXED64IVPROC glad_glGetVertexArrayIndexed64iv
Referenced by load_GL_VERSION_4_5.
PFNGLGETVERTEXARRAYINDEXEDIVPROC glad_glGetVertexArrayIndexediv
Referenced by load_GL_VERSION_4_5.
PFNGLGETVERTEXARRAYIVPROC glad_glGetVertexArrayiv
Referenced by load_GL_VERSION_4_5.
PFNGLGETVERTEXATTRIBIIVPROC glad_glGetVertexAttribIiv
Referenced by load_GL_VERSION_3_0.
PFNGLGETVERTEXATTRIBIUIVPROC glad_glGetVertexAttribIuiv
Referenced by load_GL_VERSION_3_0.
PFNGLGETVERTEXATTRIBLDVPROC glad_glGetVertexAttribLdv
Referenced by load_GL_VERSION_4_1.
PFNGLGETVERTEXATTRIBPOINTERVPROC glad_glGetVertexAttribPointerv
Referenced by load_GL_VERSION_2_0.
PFNGLGETVERTEXATTRIBDVPROC glad_glGetVertexAttribdv
Referenced by load_GL_VERSION_2_0.
PFNGLGETVERTEXATTRIBFVPROC glad_glGetVertexAttribfv
Referenced by load_GL_VERSION_2_0.
PFNGLGETVERTEXATTRIBIVPROC glad_glGetVertexAttribiv
Referenced by load_GL_VERSION_2_0.
PFNGLGETNCOLORTABLEPROC glad_glGetnColorTable
Referenced by load_GL_VERSION_4_5.
PFNGLGETNCOMPRESSEDTEXIMAGEPROC glad_glGetnCompressedTexImage
Referenced by load_GL_VERSION_4_5.
PFNGLGETNCONVOLUTIONFILTERPROC glad_glGetnConvolutionFilter
Referenced by load_GL_VERSION_4_5.
PFNGLGETNHISTOGRAMPROC glad_glGetnHistogram
Referenced by load_GL_VERSION_4_5.
PFNGLGETNMAPDVPROC glad_glGetnMapdv
Referenced by load_GL_VERSION_4_5.
PFNGLGETNMAPFVPROC glad_glGetnMapfv
Referenced by load_GL_VERSION_4_5.
PFNGLGETNMAPIVPROC glad_glGetnMapiv
Referenced by load_GL_VERSION_4_5.
PFNGLGETNMINMAXPROC glad_glGetnMinmax
Referenced by load_GL_VERSION_4_5.
PFNGLGETNPIXELMAPFVPROC glad_glGetnPixelMapfv
Referenced by load_GL_VERSION_4_5.
PFNGLGETNPIXELMAPUIVPROC glad_glGetnPixelMapuiv
Referenced by load_GL_VERSION_4_5.
PFNGLGETNPIXELMAPUSVPROC glad_glGetnPixelMapusv
Referenced by load_GL_VERSION_4_5.
PFNGLGETNPOLYGONSTIPPLEPROC glad_glGetnPolygonStipple
Referenced by load_GL_VERSION_4_5.
PFNGLGETNSEPARABLEFILTERPROC glad_glGetnSeparableFilter
Referenced by load_GL_VERSION_4_5.
PFNGLGETNTEXIMAGEPROC glad_glGetnTexImage
Referenced by load_GL_VERSION_4_5.
PFNGLGETNUNIFORMDVPROC glad_glGetnUniformdv
Referenced by load_GL_VERSION_4_5.
PFNGLGETNUNIFORMFVPROC glad_glGetnUniformfv
Referenced by load_GL_VERSION_4_5.
PFNGLGETNUNIFORMIVPROC glad_glGetnUniformiv
Referenced by load_GL_VERSION_4_5.
PFNGLGETNUNIFORMUIVPROC glad_glGetnUniformuiv
Referenced by load_GL_VERSION_4_5.
PFNGLHINTPROC glad_glHint
Referenced by load_GL_VERSION_1_0.
PFNGLINDEXMASKPROC glad_glIndexMask
Referenced by load_GL_VERSION_1_0.
PFNGLINDEXPOINTERPROC glad_glIndexPointer
Referenced by load_GL_VERSION_1_1.
PFNGLINDEXDPROC glad_glIndexd
Referenced by load_GL_VERSION_1_0.
PFNGLINDEXDVPROC glad_glIndexdv
Referenced by load_GL_VERSION_1_0.
PFNGLINDEXFPROC glad_glIndexf
Referenced by load_GL_VERSION_1_0.
PFNGLINDEXFVPROC glad_glIndexfv
Referenced by load_GL_VERSION_1_0.
PFNGLINDEXIPROC glad_glIndexi
Referenced by load_GL_VERSION_1_0.
PFNGLINDEXIVPROC glad_glIndexiv
Referenced by load_GL_VERSION_1_0.
PFNGLINDEXSPROC glad_glIndexs
Referenced by load_GL_VERSION_1_0.
PFNGLINDEXSVPROC glad_glIndexsv
Referenced by load_GL_VERSION_1_0.
PFNGLINDEXUBPROC glad_glIndexub
Referenced by load_GL_VERSION_1_1.
PFNGLINDEXUBVPROC glad_glIndexubv
Referenced by load_GL_VERSION_1_1.
PFNGLINITNAMESPROC glad_glInitNames
Referenced by load_GL_VERSION_1_0.
PFNGLINTERLEAVEDARRAYSPROC glad_glInterleavedArrays
Referenced by load_GL_VERSION_1_1.
PFNGLINVALIDATEBUFFERDATAPROC glad_glInvalidateBufferData
Referenced by load_GL_VERSION_4_3.
PFNGLINVALIDATEBUFFERSUBDATAPROC glad_glInvalidateBufferSubData
Referenced by load_GL_VERSION_4_3.
PFNGLINVALIDATEFRAMEBUFFERPROC glad_glInvalidateFramebuffer
Referenced by load_GL_VERSION_4_3.
PFNGLINVALIDATENAMEDFRAMEBUFFERDATAPROC glad_glInvalidateNamedFramebufferData
Referenced by load_GL_VERSION_4_5.
PFNGLINVALIDATENAMEDFRAMEBUFFERSUBDATAPROC glad_glInvalidateNamedFramebufferSubData
Referenced by load_GL_VERSION_4_5.
PFNGLINVALIDATESUBFRAMEBUFFERPROC glad_glInvalidateSubFramebuffer
Referenced by load_GL_VERSION_4_3.
PFNGLINVALIDATETEXIMAGEPROC glad_glInvalidateTexImage
Referenced by load_GL_VERSION_4_3.
PFNGLINVALIDATETEXSUBIMAGEPROC glad_glInvalidateTexSubImage
Referenced by load_GL_VERSION_4_3.
PFNGLISBUFFERPROC glad_glIsBuffer
Referenced by load_GL_VERSION_1_5.
PFNGLISENABLEDPROC glad_glIsEnabled
Referenced by load_GL_VERSION_1_0.
PFNGLISENABLEDIPROC glad_glIsEnabledi
Referenced by load_GL_VERSION_3_0.
PFNGLISFRAMEBUFFERPROC glad_glIsFramebuffer
Referenced by load_GL_VERSION_3_0.
PFNGLISLISTPROC glad_glIsList
Referenced by load_GL_VERSION_1_0.
PFNGLISPROGRAMPROC glad_glIsProgram
Referenced by load_GL_VERSION_2_0.
PFNGLISPROGRAMPIPELINEPROC glad_glIsProgramPipeline
Referenced by load_GL_VERSION_4_1.
PFNGLISQUERYPROC glad_glIsQuery
Referenced by load_GL_VERSION_1_5.
PFNGLISRENDERBUFFERPROC glad_glIsRenderbuffer
Referenced by load_GL_VERSION_3_0.
PFNGLISSAMPLERPROC glad_glIsSampler
Referenced by load_GL_VERSION_3_3.
PFNGLISSHADERPROC glad_glIsShader
Referenced by load_GL_VERSION_2_0.
PFNGLISSYNCPROC glad_glIsSync
Referenced by load_GL_VERSION_3_2.
PFNGLISTEXTUREPROC glad_glIsTexture
Referenced by load_GL_VERSION_1_1.
PFNGLISTRANSFORMFEEDBACKPROC glad_glIsTransformFeedback
Referenced by load_GL_VERSION_4_0.
PFNGLISVERTEXARRAYPROC glad_glIsVertexArray
Referenced by load_GL_VERSION_3_0.
PFNGLLIGHTMODELFPROC glad_glLightModelf
Referenced by load_GL_VERSION_1_0.
PFNGLLIGHTMODELFVPROC glad_glLightModelfv
Referenced by load_GL_VERSION_1_0.
PFNGLLIGHTMODELIPROC glad_glLightModeli
Referenced by load_GL_VERSION_1_0.
PFNGLLIGHTMODELIVPROC glad_glLightModeliv
Referenced by load_GL_VERSION_1_0.
PFNGLLIGHTFPROC glad_glLightf
Referenced by load_GL_VERSION_1_0.
PFNGLLIGHTFVPROC glad_glLightfv
Referenced by load_GL_VERSION_1_0.
PFNGLLIGHTIPROC glad_glLighti
Referenced by load_GL_VERSION_1_0.
PFNGLLIGHTIVPROC glad_glLightiv
Referenced by load_GL_VERSION_1_0.
PFNGLLINESTIPPLEPROC glad_glLineStipple
Referenced by load_GL_VERSION_1_0.
PFNGLLINEWIDTHPROC glad_glLineWidth
Referenced by load_GL_VERSION_1_0.
PFNGLLINKPROGRAMPROC glad_glLinkProgram
Referenced by load_GL_VERSION_2_0.
PFNGLLISTBASEPROC glad_glListBase
Referenced by load_GL_VERSION_1_0.
PFNGLLOADIDENTITYPROC glad_glLoadIdentity
Referenced by load_GL_VERSION_1_0.
PFNGLLOADMATRIXDPROC glad_glLoadMatrixd
Referenced by load_GL_VERSION_1_0.
PFNGLLOADMATRIXFPROC glad_glLoadMatrixf
Referenced by load_GL_VERSION_1_0.
PFNGLLOADNAMEPROC glad_glLoadName
Referenced by load_GL_VERSION_1_0.
PFNGLLOADTRANSPOSEMATRIXDPROC glad_glLoadTransposeMatrixd
Referenced by load_GL_VERSION_1_3.
PFNGLLOADTRANSPOSEMATRIXFPROC glad_glLoadTransposeMatrixf
Referenced by load_GL_VERSION_1_3.
PFNGLLOGICOPPROC glad_glLogicOp
Referenced by load_GL_VERSION_1_0.
PFNGLMAP1DPROC glad_glMap1d
Referenced by load_GL_VERSION_1_0.
PFNGLMAP1FPROC glad_glMap1f
Referenced by load_GL_VERSION_1_0.
PFNGLMAP2DPROC glad_glMap2d
Referenced by load_GL_VERSION_1_0.
PFNGLMAP2FPROC glad_glMap2f
Referenced by load_GL_VERSION_1_0.
PFNGLMAPBUFFERPROC glad_glMapBuffer
Referenced by load_GL_VERSION_1_5.
PFNGLMAPBUFFERRANGEPROC glad_glMapBufferRange
Referenced by load_GL_VERSION_3_0.
PFNGLMAPGRID1DPROC glad_glMapGrid1d
Referenced by load_GL_VERSION_1_0.
PFNGLMAPGRID1FPROC glad_glMapGrid1f
Referenced by load_GL_VERSION_1_0.
PFNGLMAPGRID2DPROC glad_glMapGrid2d
Referenced by load_GL_VERSION_1_0.
PFNGLMAPGRID2FPROC glad_glMapGrid2f
Referenced by load_GL_VERSION_1_0.
PFNGLMAPNAMEDBUFFERPROC glad_glMapNamedBuffer
Referenced by load_GL_VERSION_4_5.
PFNGLMAPNAMEDBUFFERRANGEPROC glad_glMapNamedBufferRange
Referenced by load_GL_VERSION_4_5.
PFNGLMATERIALFPROC glad_glMaterialf
Referenced by load_GL_VERSION_1_0.
PFNGLMATERIALFVPROC glad_glMaterialfv
Referenced by load_GL_VERSION_1_0.
PFNGLMATERIALIPROC glad_glMateriali
Referenced by load_GL_VERSION_1_0.
PFNGLMATERIALIVPROC glad_glMaterialiv
Referenced by load_GL_VERSION_1_0.
PFNGLMATRIXMODEPROC glad_glMatrixMode
Referenced by load_GL_VERSION_1_0.
PFNGLMEMORYBARRIERPROC glad_glMemoryBarrier
Referenced by load_GL_VERSION_4_2.
PFNGLMEMORYBARRIERBYREGIONPROC glad_glMemoryBarrierByRegion
Referenced by load_GL_VERSION_4_5.
PFNGLMINSAMPLESHADINGPROC glad_glMinSampleShading
Referenced by load_GL_VERSION_4_0.
PFNGLMULTMATRIXDPROC glad_glMultMatrixd
Referenced by load_GL_VERSION_1_0.
PFNGLMULTMATRIXFPROC glad_glMultMatrixf
Referenced by load_GL_VERSION_1_0.
PFNGLMULTTRANSPOSEMATRIXDPROC glad_glMultTransposeMatrixd
Referenced by load_GL_VERSION_1_3.
PFNGLMULTTRANSPOSEMATRIXFPROC glad_glMultTransposeMatrixf
Referenced by load_GL_VERSION_1_3.
PFNGLMULTIDRAWARRAYSPROC glad_glMultiDrawArrays
Referenced by load_GL_VERSION_1_4.
PFNGLMULTIDRAWARRAYSINDIRECTPROC glad_glMultiDrawArraysIndirect
Referenced by load_GL_VERSION_4_3.
PFNGLMULTIDRAWELEMENTSPROC glad_glMultiDrawElements
Referenced by load_GL_VERSION_1_4.
PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC glad_glMultiDrawElementsBaseVertex
Referenced by load_GL_VERSION_3_2.
PFNGLMULTIDRAWELEMENTSINDIRECTPROC glad_glMultiDrawElementsIndirect
Referenced by load_GL_VERSION_4_3.
PFNGLMULTITEXCOORD1DPROC glad_glMultiTexCoord1d
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD1DVPROC glad_glMultiTexCoord1dv
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD1FPROC glad_glMultiTexCoord1f
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD1FVPROC glad_glMultiTexCoord1fv
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD1IPROC glad_glMultiTexCoord1i
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD1IVPROC glad_glMultiTexCoord1iv
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD1SPROC glad_glMultiTexCoord1s
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD1SVPROC glad_glMultiTexCoord1sv
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD2DPROC glad_glMultiTexCoord2d
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD2DVPROC glad_glMultiTexCoord2dv
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD2FPROC glad_glMultiTexCoord2f
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD2FVPROC glad_glMultiTexCoord2fv
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD2IPROC glad_glMultiTexCoord2i
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD2IVPROC glad_glMultiTexCoord2iv
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD2SPROC glad_glMultiTexCoord2s
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD2SVPROC glad_glMultiTexCoord2sv
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD3DPROC glad_glMultiTexCoord3d
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD3DVPROC glad_glMultiTexCoord3dv
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD3FPROC glad_glMultiTexCoord3f
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD3FVPROC glad_glMultiTexCoord3fv
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD3IPROC glad_glMultiTexCoord3i
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD3IVPROC glad_glMultiTexCoord3iv
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD3SPROC glad_glMultiTexCoord3s
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD3SVPROC glad_glMultiTexCoord3sv
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD4DPROC glad_glMultiTexCoord4d
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD4DVPROC glad_glMultiTexCoord4dv
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD4FPROC glad_glMultiTexCoord4f
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD4FVPROC glad_glMultiTexCoord4fv
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD4IPROC glad_glMultiTexCoord4i
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD4IVPROC glad_glMultiTexCoord4iv
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD4SPROC glad_glMultiTexCoord4s
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORD4SVPROC glad_glMultiTexCoord4sv
Referenced by load_GL_VERSION_1_3.
PFNGLMULTITEXCOORDP1UIPROC glad_glMultiTexCoordP1ui
Referenced by load_GL_VERSION_3_3.
PFNGLMULTITEXCOORDP1UIVPROC glad_glMultiTexCoordP1uiv
Referenced by load_GL_VERSION_3_3.
PFNGLMULTITEXCOORDP2UIPROC glad_glMultiTexCoordP2ui
Referenced by load_GL_VERSION_3_3.
PFNGLMULTITEXCOORDP2UIVPROC glad_glMultiTexCoordP2uiv
Referenced by load_GL_VERSION_3_3.
PFNGLMULTITEXCOORDP3UIPROC glad_glMultiTexCoordP3ui
Referenced by load_GL_VERSION_3_3.
PFNGLMULTITEXCOORDP3UIVPROC glad_glMultiTexCoordP3uiv
Referenced by load_GL_VERSION_3_3.
PFNGLMULTITEXCOORDP4UIPROC glad_glMultiTexCoordP4ui
Referenced by load_GL_VERSION_3_3.
PFNGLMULTITEXCOORDP4UIVPROC glad_glMultiTexCoordP4uiv
Referenced by load_GL_VERSION_3_3.
PFNGLNAMEDBUFFERDATAPROC glad_glNamedBufferData
Referenced by load_GL_VERSION_4_5.
PFNGLNAMEDBUFFERSTORAGEPROC glad_glNamedBufferStorage
Referenced by load_GL_VERSION_4_5.
PFNGLNAMEDBUFFERSUBDATAPROC glad_glNamedBufferSubData
Referenced by load_GL_VERSION_4_5.
PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC glad_glNamedFramebufferDrawBuffer
Referenced by load_GL_VERSION_4_5.
PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC glad_glNamedFramebufferDrawBuffers
Referenced by load_GL_VERSION_4_5.
PFNGLNAMEDFRAMEBUFFERPARAMETERIPROC glad_glNamedFramebufferParameteri
Referenced by load_GL_VERSION_4_5.
PFNGLNAMEDFRAMEBUFFERREADBUFFERPROC glad_glNamedFramebufferReadBuffer
Referenced by load_GL_VERSION_4_5.
PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC glad_glNamedFramebufferRenderbuffer
Referenced by load_GL_VERSION_4_5.
PFNGLNAMEDFRAMEBUFFERTEXTUREPROC glad_glNamedFramebufferTexture
Referenced by load_GL_VERSION_4_5.
PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC glad_glNamedFramebufferTextureLayer
Referenced by load_GL_VERSION_4_5.
PFNGLNAMEDRENDERBUFFERSTORAGEPROC glad_glNamedRenderbufferStorage
Referenced by load_GL_VERSION_4_5.
PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEPROC glad_glNamedRenderbufferStorageMultisample
Referenced by load_GL_VERSION_4_5.
PFNGLNEWLISTPROC glad_glNewList
Referenced by load_GL_VERSION_1_0.
PFNGLNORMAL3BPROC glad_glNormal3b
Referenced by load_GL_VERSION_1_0.
PFNGLNORMAL3BVPROC glad_glNormal3bv
Referenced by load_GL_VERSION_1_0.
PFNGLNORMAL3DPROC glad_glNormal3d
Referenced by load_GL_VERSION_1_0.
PFNGLNORMAL3DVPROC glad_glNormal3dv
Referenced by load_GL_VERSION_1_0.
PFNGLNORMAL3FPROC glad_glNormal3f
Referenced by load_GL_VERSION_1_0.
PFNGLNORMAL3FVPROC glad_glNormal3fv
Referenced by load_GL_VERSION_1_0.
PFNGLNORMAL3IPROC glad_glNormal3i
Referenced by load_GL_VERSION_1_0.
PFNGLNORMAL3IVPROC glad_glNormal3iv
Referenced by load_GL_VERSION_1_0.
PFNGLNORMAL3SPROC glad_glNormal3s
Referenced by load_GL_VERSION_1_0.
PFNGLNORMAL3SVPROC glad_glNormal3sv
Referenced by load_GL_VERSION_1_0.
PFNGLNORMALP3UIPROC glad_glNormalP3ui
Referenced by load_GL_VERSION_3_3.
PFNGLNORMALP3UIVPROC glad_glNormalP3uiv
Referenced by load_GL_VERSION_3_3.
PFNGLNORMALPOINTERPROC glad_glNormalPointer
Referenced by load_GL_VERSION_1_1.
PFNGLOBJECTLABELPROC glad_glObjectLabel
Referenced by load_GL_VERSION_4_3.
PFNGLOBJECTPTRLABELPROC glad_glObjectPtrLabel
Referenced by load_GL_VERSION_4_3.
PFNGLORTHOPROC glad_glOrtho
Referenced by load_GL_VERSION_1_0.
PFNGLPASSTHROUGHPROC glad_glPassThrough
Referenced by load_GL_VERSION_1_0.
PFNGLPATCHPARAMETERFVPROC glad_glPatchParameterfv
Referenced by load_GL_VERSION_4_0.
PFNGLPATCHPARAMETERIPROC glad_glPatchParameteri
Referenced by load_GL_VERSION_4_0.
PFNGLPAUSETRANSFORMFEEDBACKPROC glad_glPauseTransformFeedback
Referenced by load_GL_VERSION_4_0.
PFNGLPIXELMAPFVPROC glad_glPixelMapfv
Referenced by load_GL_VERSION_1_0.
PFNGLPIXELMAPUIVPROC glad_glPixelMapuiv
Referenced by load_GL_VERSION_1_0.
PFNGLPIXELMAPUSVPROC glad_glPixelMapusv
Referenced by load_GL_VERSION_1_0.
PFNGLPIXELSTOREFPROC glad_glPixelStoref
Referenced by load_GL_VERSION_1_0.
PFNGLPIXELSTOREIPROC glad_glPixelStorei
Referenced by load_GL_VERSION_1_0.
PFNGLPIXELTRANSFERFPROC glad_glPixelTransferf
Referenced by load_GL_VERSION_1_0.
PFNGLPIXELTRANSFERIPROC glad_glPixelTransferi
Referenced by load_GL_VERSION_1_0.
PFNGLPIXELZOOMPROC glad_glPixelZoom
Referenced by load_GL_VERSION_1_0.
PFNGLPOINTPARAMETERFPROC glad_glPointParameterf
Referenced by load_GL_VERSION_1_4.
PFNGLPOINTPARAMETERFVPROC glad_glPointParameterfv
Referenced by load_GL_VERSION_1_4.
PFNGLPOINTPARAMETERIPROC glad_glPointParameteri
Referenced by load_GL_VERSION_1_4.
PFNGLPOINTPARAMETERIVPROC glad_glPointParameteriv
Referenced by load_GL_VERSION_1_4.
PFNGLPOINTSIZEPROC glad_glPointSize
Referenced by load_GL_VERSION_1_0.
PFNGLPOLYGONMODEPROC glad_glPolygonMode
Referenced by load_GL_VERSION_1_0.
PFNGLPOLYGONOFFSETPROC glad_glPolygonOffset
Referenced by load_GL_VERSION_1_1.
PFNGLPOLYGONSTIPPLEPROC glad_glPolygonStipple
Referenced by load_GL_VERSION_1_0.
PFNGLPOPATTRIBPROC glad_glPopAttrib
Referenced by load_GL_VERSION_1_0.
PFNGLPOPCLIENTATTRIBPROC glad_glPopClientAttrib
Referenced by load_GL_VERSION_1_1.
PFNGLPOPDEBUGGROUPPROC glad_glPopDebugGroup
Referenced by load_GL_VERSION_4_3.
PFNGLPOPMATRIXPROC glad_glPopMatrix
Referenced by load_GL_VERSION_1_0.
PFNGLPOPNAMEPROC glad_glPopName
Referenced by load_GL_VERSION_1_0.
PFNGLPRIMITIVERESTARTINDEXPROC glad_glPrimitiveRestartIndex
Referenced by load_GL_VERSION_3_1.
PFNGLPRIORITIZETEXTURESPROC glad_glPrioritizeTextures
Referenced by load_GL_VERSION_1_1.
PFNGLPROGRAMBINARYPROC glad_glProgramBinary
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMPARAMETERIPROC glad_glProgramParameteri
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM1DPROC glad_glProgramUniform1d
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM1DVPROC glad_glProgramUniform1dv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM1FPROC glad_glProgramUniform1f
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM1FVPROC glad_glProgramUniform1fv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM1IPROC glad_glProgramUniform1i
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM1IVPROC glad_glProgramUniform1iv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM1UIPROC glad_glProgramUniform1ui
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM1UIVPROC glad_glProgramUniform1uiv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM2DPROC glad_glProgramUniform2d
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM2DVPROC glad_glProgramUniform2dv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM2FPROC glad_glProgramUniform2f
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM2FVPROC glad_glProgramUniform2fv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM2IPROC glad_glProgramUniform2i
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM2IVPROC glad_glProgramUniform2iv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM2UIPROC glad_glProgramUniform2ui
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM2UIVPROC glad_glProgramUniform2uiv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM3DPROC glad_glProgramUniform3d
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM3DVPROC glad_glProgramUniform3dv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM3FPROC glad_glProgramUniform3f
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM3FVPROC glad_glProgramUniform3fv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM3IPROC glad_glProgramUniform3i
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM3IVPROC glad_glProgramUniform3iv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM3UIPROC glad_glProgramUniform3ui
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM3UIVPROC glad_glProgramUniform3uiv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM4DPROC glad_glProgramUniform4d
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM4DVPROC glad_glProgramUniform4dv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM4FPROC glad_glProgramUniform4f
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM4FVPROC glad_glProgramUniform4fv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM4IPROC glad_glProgramUniform4i
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM4IVPROC glad_glProgramUniform4iv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM4UIPROC glad_glProgramUniform4ui
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORM4UIVPROC glad_glProgramUniform4uiv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX2DVPROC glad_glProgramUniformMatrix2dv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX2FVPROC glad_glProgramUniformMatrix2fv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC glad_glProgramUniformMatrix2x3dv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC glad_glProgramUniformMatrix2x3fv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC glad_glProgramUniformMatrix2x4dv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC glad_glProgramUniformMatrix2x4fv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX3DVPROC glad_glProgramUniformMatrix3dv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX3FVPROC glad_glProgramUniformMatrix3fv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC glad_glProgramUniformMatrix3x2dv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC glad_glProgramUniformMatrix3x2fv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC glad_glProgramUniformMatrix3x4dv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC glad_glProgramUniformMatrix3x4fv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX4DVPROC glad_glProgramUniformMatrix4dv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX4FVPROC glad_glProgramUniformMatrix4fv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC glad_glProgramUniformMatrix4x2dv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC glad_glProgramUniformMatrix4x2fv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC glad_glProgramUniformMatrix4x3dv
Referenced by load_GL_VERSION_4_1.
PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC glad_glProgramUniformMatrix4x3fv
Referenced by load_GL_VERSION_4_1.
PFNGLPROVOKINGVERTEXPROC glad_glProvokingVertex
Referenced by load_GL_VERSION_3_2.
PFNGLPUSHATTRIBPROC glad_glPushAttrib
Referenced by load_GL_VERSION_1_0.
PFNGLPUSHCLIENTATTRIBPROC glad_glPushClientAttrib
Referenced by load_GL_VERSION_1_1.
PFNGLPUSHDEBUGGROUPPROC glad_glPushDebugGroup
Referenced by load_GL_VERSION_4_3.
PFNGLPUSHMATRIXPROC glad_glPushMatrix
Referenced by load_GL_VERSION_1_0.
PFNGLPUSHNAMEPROC glad_glPushName
Referenced by load_GL_VERSION_1_0.
PFNGLQUERYCOUNTERPROC glad_glQueryCounter
Referenced by load_GL_VERSION_3_3.
PFNGLRASTERPOS2DPROC glad_glRasterPos2d
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS2DVPROC glad_glRasterPos2dv
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS2FPROC glad_glRasterPos2f
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS2FVPROC glad_glRasterPos2fv
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS2IPROC glad_glRasterPos2i
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS2IVPROC glad_glRasterPos2iv
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS2SPROC glad_glRasterPos2s
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS2SVPROC glad_glRasterPos2sv
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS3DPROC glad_glRasterPos3d
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS3DVPROC glad_glRasterPos3dv
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS3FPROC glad_glRasterPos3f
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS3FVPROC glad_glRasterPos3fv
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS3IPROC glad_glRasterPos3i
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS3IVPROC glad_glRasterPos3iv
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS3SPROC glad_glRasterPos3s
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS3SVPROC glad_glRasterPos3sv
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS4DPROC glad_glRasterPos4d
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS4DVPROC glad_glRasterPos4dv
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS4FPROC glad_glRasterPos4f
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS4FVPROC glad_glRasterPos4fv
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS4IPROC glad_glRasterPos4i
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS4IVPROC glad_glRasterPos4iv
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS4SPROC glad_glRasterPos4s
Referenced by load_GL_VERSION_1_0.
PFNGLRASTERPOS4SVPROC glad_glRasterPos4sv
Referenced by load_GL_VERSION_1_0.
PFNGLREADBUFFERPROC glad_glReadBuffer
Referenced by load_GL_VERSION_1_0.
PFNGLREADPIXELSPROC glad_glReadPixels
Referenced by load_GL_VERSION_1_0.
PFNGLREADNPIXELSPROC glad_glReadnPixels
Referenced by load_GL_VERSION_4_5.
PFNGLRECTDPROC glad_glRectd
Referenced by load_GL_VERSION_1_0.
PFNGLRECTDVPROC glad_glRectdv
Referenced by load_GL_VERSION_1_0.
PFNGLRECTFPROC glad_glRectf
Referenced by load_GL_VERSION_1_0.
PFNGLRECTFVPROC glad_glRectfv
Referenced by load_GL_VERSION_1_0.
PFNGLRECTIPROC glad_glRecti
Referenced by load_GL_VERSION_1_0.
PFNGLRECTIVPROC glad_glRectiv
Referenced by load_GL_VERSION_1_0.
PFNGLRECTSPROC glad_glRects
Referenced by load_GL_VERSION_1_0.
PFNGLRECTSVPROC glad_glRectsv
Referenced by load_GL_VERSION_1_0.
PFNGLRELEASESHADERCOMPILERPROC glad_glReleaseShaderCompiler
Referenced by load_GL_VERSION_4_1.
PFNGLRENDERMODEPROC glad_glRenderMode
Referenced by load_GL_VERSION_1_0.
PFNGLRENDERBUFFERSTORAGEPROC glad_glRenderbufferStorage
Referenced by load_GL_VERSION_3_0.
PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glad_glRenderbufferStorageMultisample
Referenced by load_GL_VERSION_3_0.
PFNGLRESUMETRANSFORMFEEDBACKPROC glad_glResumeTransformFeedback
Referenced by load_GL_VERSION_4_0.
PFNGLROTATEDPROC glad_glRotated
Referenced by load_GL_VERSION_1_0.
PFNGLROTATEFPROC glad_glRotatef
Referenced by load_GL_VERSION_1_0.
PFNGLSAMPLECOVERAGEPROC glad_glSampleCoverage
Referenced by load_GL_VERSION_1_3.
PFNGLSAMPLEMASKIPROC glad_glSampleMaski
Referenced by load_GL_VERSION_3_2.
PFNGLSAMPLERPARAMETERIIVPROC glad_glSamplerParameterIiv
Referenced by load_GL_VERSION_3_3.
PFNGLSAMPLERPARAMETERIUIVPROC glad_glSamplerParameterIuiv
Referenced by load_GL_VERSION_3_3.
PFNGLSAMPLERPARAMETERFPROC glad_glSamplerParameterf
Referenced by load_GL_VERSION_3_3.
PFNGLSAMPLERPARAMETERFVPROC glad_glSamplerParameterfv
Referenced by load_GL_VERSION_3_3.
PFNGLSAMPLERPARAMETERIPROC glad_glSamplerParameteri
Referenced by load_GL_VERSION_3_3.
PFNGLSAMPLERPARAMETERIVPROC glad_glSamplerParameteriv
Referenced by load_GL_VERSION_3_3.
PFNGLSCALEDPROC glad_glScaled
Referenced by load_GL_VERSION_1_0.
PFNGLSCALEFPROC glad_glScalef
Referenced by load_GL_VERSION_1_0.
PFNGLSCISSORPROC glad_glScissor
Referenced by load_GL_VERSION_1_0.
PFNGLSCISSORARRAYVPROC glad_glScissorArrayv
Referenced by load_GL_VERSION_4_1.
PFNGLSCISSORINDEXEDPROC glad_glScissorIndexed
Referenced by load_GL_VERSION_4_1.
PFNGLSCISSORINDEXEDVPROC glad_glScissorIndexedv
Referenced by load_GL_VERSION_4_1.
PFNGLSECONDARYCOLOR3BPROC glad_glSecondaryColor3b
Referenced by load_GL_VERSION_1_4.
PFNGLSECONDARYCOLOR3BVPROC glad_glSecondaryColor3bv
Referenced by load_GL_VERSION_1_4.
PFNGLSECONDARYCOLOR3DPROC glad_glSecondaryColor3d
Referenced by load_GL_VERSION_1_4.
PFNGLSECONDARYCOLOR3DVPROC glad_glSecondaryColor3dv
Referenced by load_GL_VERSION_1_4.
PFNGLSECONDARYCOLOR3FPROC glad_glSecondaryColor3f
Referenced by load_GL_VERSION_1_4.
PFNGLSECONDARYCOLOR3FVPROC glad_glSecondaryColor3fv
Referenced by load_GL_VERSION_1_4.
PFNGLSECONDARYCOLOR3IPROC glad_glSecondaryColor3i
Referenced by load_GL_VERSION_1_4.
PFNGLSECONDARYCOLOR3IVPROC glad_glSecondaryColor3iv
Referenced by load_GL_VERSION_1_4.
PFNGLSECONDARYCOLOR3SPROC glad_glSecondaryColor3s
Referenced by load_GL_VERSION_1_4.
PFNGLSECONDARYCOLOR3SVPROC glad_glSecondaryColor3sv
Referenced by load_GL_VERSION_1_4.
PFNGLSECONDARYCOLOR3UBPROC glad_glSecondaryColor3ub
Referenced by load_GL_VERSION_1_4.
PFNGLSECONDARYCOLOR3UBVPROC glad_glSecondaryColor3ubv
Referenced by load_GL_VERSION_1_4.
PFNGLSECONDARYCOLOR3UIPROC glad_glSecondaryColor3ui
Referenced by load_GL_VERSION_1_4.
PFNGLSECONDARYCOLOR3UIVPROC glad_glSecondaryColor3uiv
Referenced by load_GL_VERSION_1_4.
PFNGLSECONDARYCOLOR3USPROC glad_glSecondaryColor3us
Referenced by load_GL_VERSION_1_4.
PFNGLSECONDARYCOLOR3USVPROC glad_glSecondaryColor3usv
Referenced by load_GL_VERSION_1_4.
PFNGLSECONDARYCOLORP3UIPROC glad_glSecondaryColorP3ui
Referenced by load_GL_VERSION_3_3.
PFNGLSECONDARYCOLORP3UIVPROC glad_glSecondaryColorP3uiv
Referenced by load_GL_VERSION_3_3.
PFNGLSECONDARYCOLORPOINTERPROC glad_glSecondaryColorPointer
Referenced by load_GL_VERSION_1_4.
PFNGLSELECTBUFFERPROC glad_glSelectBuffer
Referenced by load_GL_VERSION_1_0.
PFNGLSHADEMODELPROC glad_glShadeModel
Referenced by load_GL_VERSION_1_0.
PFNGLSHADERBINARYPROC glad_glShaderBinary
Referenced by load_GL_VERSION_4_1.
PFNGLSHADERSOURCEPROC glad_glShaderSource
Referenced by load_GL_VERSION_2_0.
PFNGLSHADERSTORAGEBLOCKBINDINGPROC glad_glShaderStorageBlockBinding
Referenced by load_GL_VERSION_4_3.
PFNGLSTENCILFUNCPROC glad_glStencilFunc
Referenced by load_GL_VERSION_1_0.
PFNGLSTENCILFUNCSEPARATEPROC glad_glStencilFuncSeparate
Referenced by load_GL_VERSION_2_0.
PFNGLSTENCILMASKPROC glad_glStencilMask
Referenced by load_GL_VERSION_1_0.
PFNGLSTENCILMASKSEPARATEPROC glad_glStencilMaskSeparate
Referenced by load_GL_VERSION_2_0.
PFNGLSTENCILOPPROC glad_glStencilOp
Referenced by load_GL_VERSION_1_0.
PFNGLSTENCILOPSEPARATEPROC glad_glStencilOpSeparate
Referenced by load_GL_VERSION_2_0.
PFNGLTEXBUFFERPROC glad_glTexBuffer
Referenced by load_GL_VERSION_3_1.
PFNGLTEXBUFFERRANGEPROC glad_glTexBufferRange
Referenced by load_GL_VERSION_4_3.
PFNGLTEXCOORD1DPROC glad_glTexCoord1d
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD1DVPROC glad_glTexCoord1dv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD1FPROC glad_glTexCoord1f
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD1FVPROC glad_glTexCoord1fv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD1IPROC glad_glTexCoord1i
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD1IVPROC glad_glTexCoord1iv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD1SPROC glad_glTexCoord1s
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD1SVPROC glad_glTexCoord1sv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD2DPROC glad_glTexCoord2d
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD2DVPROC glad_glTexCoord2dv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD2FPROC glad_glTexCoord2f
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD2FVPROC glad_glTexCoord2fv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD2IPROC glad_glTexCoord2i
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD2IVPROC glad_glTexCoord2iv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD2SPROC glad_glTexCoord2s
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD2SVPROC glad_glTexCoord2sv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD3DPROC glad_glTexCoord3d
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD3DVPROC glad_glTexCoord3dv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD3FPROC glad_glTexCoord3f
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD3FVPROC glad_glTexCoord3fv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD3IPROC glad_glTexCoord3i
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD3IVPROC glad_glTexCoord3iv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD3SPROC glad_glTexCoord3s
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD3SVPROC glad_glTexCoord3sv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD4DPROC glad_glTexCoord4d
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD4DVPROC glad_glTexCoord4dv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD4FPROC glad_glTexCoord4f
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD4FVPROC glad_glTexCoord4fv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD4IPROC glad_glTexCoord4i
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD4IVPROC glad_glTexCoord4iv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD4SPROC glad_glTexCoord4s
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORD4SVPROC glad_glTexCoord4sv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXCOORDP1UIPROC glad_glTexCoordP1ui
Referenced by load_GL_VERSION_3_3.
PFNGLTEXCOORDP1UIVPROC glad_glTexCoordP1uiv
Referenced by load_GL_VERSION_3_3.
PFNGLTEXCOORDP2UIPROC glad_glTexCoordP2ui
Referenced by load_GL_VERSION_3_3.
PFNGLTEXCOORDP2UIVPROC glad_glTexCoordP2uiv
Referenced by load_GL_VERSION_3_3.
PFNGLTEXCOORDP3UIPROC glad_glTexCoordP3ui
Referenced by load_GL_VERSION_3_3.
PFNGLTEXCOORDP3UIVPROC glad_glTexCoordP3uiv
Referenced by load_GL_VERSION_3_3.
PFNGLTEXCOORDP4UIPROC glad_glTexCoordP4ui
Referenced by load_GL_VERSION_3_3.
PFNGLTEXCOORDP4UIVPROC glad_glTexCoordP4uiv
Referenced by load_GL_VERSION_3_3.
PFNGLTEXCOORDPOINTERPROC glad_glTexCoordPointer
Referenced by load_GL_VERSION_1_1.
PFNGLTEXENVFPROC glad_glTexEnvf
Referenced by load_GL_VERSION_1_0.
PFNGLTEXENVFVPROC glad_glTexEnvfv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXENVIPROC glad_glTexEnvi
Referenced by load_GL_VERSION_1_0.
PFNGLTEXENVIVPROC glad_glTexEnviv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXGENDPROC glad_glTexGend
Referenced by load_GL_VERSION_1_0.
PFNGLTEXGENDVPROC glad_glTexGendv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXGENFPROC glad_glTexGenf
Referenced by load_GL_VERSION_1_0.
PFNGLTEXGENFVPROC glad_glTexGenfv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXGENIPROC glad_glTexGeni
Referenced by load_GL_VERSION_1_0.
PFNGLTEXGENIVPROC glad_glTexGeniv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXIMAGE1DPROC glad_glTexImage1D
Referenced by load_GL_VERSION_1_0.
PFNGLTEXIMAGE2DPROC glad_glTexImage2D
Referenced by load_GL_VERSION_1_0.
PFNGLTEXIMAGE2DMULTISAMPLEPROC glad_glTexImage2DMultisample
Referenced by load_GL_VERSION_3_2.
PFNGLTEXIMAGE3DPROC glad_glTexImage3D
Referenced by load_GL_VERSION_1_2.
PFNGLTEXIMAGE3DMULTISAMPLEPROC glad_glTexImage3DMultisample
Referenced by load_GL_VERSION_3_2.
PFNGLTEXPARAMETERIIVPROC glad_glTexParameterIiv
Referenced by load_GL_VERSION_3_0.
PFNGLTEXPARAMETERIUIVPROC glad_glTexParameterIuiv
Referenced by load_GL_VERSION_3_0.
PFNGLTEXPARAMETERFPROC glad_glTexParameterf
Referenced by load_GL_VERSION_1_0.
PFNGLTEXPARAMETERFVPROC glad_glTexParameterfv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXPARAMETERIPROC glad_glTexParameteri
Referenced by load_GL_VERSION_1_0.
PFNGLTEXPARAMETERIVPROC glad_glTexParameteriv
Referenced by load_GL_VERSION_1_0.
PFNGLTEXSTORAGE1DPROC glad_glTexStorage1D
Referenced by load_GL_VERSION_4_2.
PFNGLTEXSTORAGE2DPROC glad_glTexStorage2D
Referenced by load_GL_VERSION_4_2.
PFNGLTEXSTORAGE2DMULTISAMPLEPROC glad_glTexStorage2DMultisample
Referenced by load_GL_VERSION_4_3.
PFNGLTEXSTORAGE3DPROC glad_glTexStorage3D
Referenced by load_GL_VERSION_4_2.
PFNGLTEXSTORAGE3DMULTISAMPLEPROC glad_glTexStorage3DMultisample
Referenced by load_GL_VERSION_4_3.
PFNGLTEXSUBIMAGE1DPROC glad_glTexSubImage1D
Referenced by load_GL_VERSION_1_1.
PFNGLTEXSUBIMAGE2DPROC glad_glTexSubImage2D
Referenced by load_GL_VERSION_1_1.
PFNGLTEXSUBIMAGE3DPROC glad_glTexSubImage3D
Referenced by load_GL_VERSION_1_2.
PFNGLTEXTUREBARRIERPROC glad_glTextureBarrier
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTUREBUFFERPROC glad_glTextureBuffer
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTUREBUFFERRANGEPROC glad_glTextureBufferRange
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTUREPARAMETERIIVPROC glad_glTextureParameterIiv
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTUREPARAMETERIUIVPROC glad_glTextureParameterIuiv
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTUREPARAMETERFPROC glad_glTextureParameterf
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTUREPARAMETERFVPROC glad_glTextureParameterfv
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTUREPARAMETERIPROC glad_glTextureParameteri
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTUREPARAMETERIVPROC glad_glTextureParameteriv
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTURESTORAGE1DPROC glad_glTextureStorage1D
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTURESTORAGE2DPROC glad_glTextureStorage2D
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTURESTORAGE2DMULTISAMPLEPROC glad_glTextureStorage2DMultisample
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTURESTORAGE3DPROC glad_glTextureStorage3D
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTURESTORAGE3DMULTISAMPLEPROC glad_glTextureStorage3DMultisample
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTURESUBIMAGE1DPROC glad_glTextureSubImage1D
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTURESUBIMAGE2DPROC glad_glTextureSubImage2D
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTURESUBIMAGE3DPROC glad_glTextureSubImage3D
Referenced by load_GL_VERSION_4_5.
PFNGLTEXTUREVIEWPROC glad_glTextureView
Referenced by load_GL_VERSION_4_3.
PFNGLTRANSFORMFEEDBACKBUFFERBASEPROC glad_glTransformFeedbackBufferBase
Referenced by load_GL_VERSION_4_5.
PFNGLTRANSFORMFEEDBACKBUFFERRANGEPROC glad_glTransformFeedbackBufferRange
Referenced by load_GL_VERSION_4_5.
PFNGLTRANSFORMFEEDBACKVARYINGSPROC glad_glTransformFeedbackVaryings
Referenced by load_GL_VERSION_3_0.
PFNGLTRANSLATEDPROC glad_glTranslated
Referenced by load_GL_VERSION_1_0.
PFNGLTRANSLATEFPROC glad_glTranslatef
Referenced by load_GL_VERSION_1_0.
PFNGLUNIFORM1DPROC glad_glUniform1d
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORM1DVPROC glad_glUniform1dv
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORM1FPROC glad_glUniform1f
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORM1FVPROC glad_glUniform1fv
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORM1IPROC glad_glUniform1i
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORM1IVPROC glad_glUniform1iv
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORM1UIPROC glad_glUniform1ui
Referenced by load_GL_VERSION_3_0.
PFNGLUNIFORM1UIVPROC glad_glUniform1uiv
Referenced by load_GL_VERSION_3_0.
PFNGLUNIFORM2DPROC glad_glUniform2d
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORM2DVPROC glad_glUniform2dv
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORM2FPROC glad_glUniform2f
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORM2FVPROC glad_glUniform2fv
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORM2IPROC glad_glUniform2i
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORM2IVPROC glad_glUniform2iv
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORM2UIPROC glad_glUniform2ui
Referenced by load_GL_VERSION_3_0.
PFNGLUNIFORM2UIVPROC glad_glUniform2uiv
Referenced by load_GL_VERSION_3_0.
PFNGLUNIFORM3DPROC glad_glUniform3d
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORM3DVPROC glad_glUniform3dv
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORM3FPROC glad_glUniform3f
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORM3FVPROC glad_glUniform3fv
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORM3IPROC glad_glUniform3i
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORM3IVPROC glad_glUniform3iv
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORM3UIPROC glad_glUniform3ui
Referenced by load_GL_VERSION_3_0.
PFNGLUNIFORM3UIVPROC glad_glUniform3uiv
Referenced by load_GL_VERSION_3_0.
PFNGLUNIFORM4DPROC glad_glUniform4d
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORM4DVPROC glad_glUniform4dv
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORM4FPROC glad_glUniform4f
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORM4FVPROC glad_glUniform4fv
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORM4IPROC glad_glUniform4i
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORM4IVPROC glad_glUniform4iv
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORM4UIPROC glad_glUniform4ui
Referenced by load_GL_VERSION_3_0.
PFNGLUNIFORM4UIVPROC glad_glUniform4uiv
Referenced by load_GL_VERSION_3_0.
PFNGLUNIFORMBLOCKBINDINGPROC glad_glUniformBlockBinding
Referenced by load_GL_VERSION_3_1.
PFNGLUNIFORMMATRIX2DVPROC glad_glUniformMatrix2dv
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORMMATRIX2FVPROC glad_glUniformMatrix2fv
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORMMATRIX2X3DVPROC glad_glUniformMatrix2x3dv
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORMMATRIX2X3FVPROC glad_glUniformMatrix2x3fv
Referenced by load_GL_VERSION_2_1.
PFNGLUNIFORMMATRIX2X4DVPROC glad_glUniformMatrix2x4dv
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORMMATRIX2X4FVPROC glad_glUniformMatrix2x4fv
Referenced by load_GL_VERSION_2_1.
PFNGLUNIFORMMATRIX3DVPROC glad_glUniformMatrix3dv
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORMMATRIX3FVPROC glad_glUniformMatrix3fv
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORMMATRIX3X2DVPROC glad_glUniformMatrix3x2dv
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORMMATRIX3X2FVPROC glad_glUniformMatrix3x2fv
Referenced by load_GL_VERSION_2_1.
PFNGLUNIFORMMATRIX3X4DVPROC glad_glUniformMatrix3x4dv
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORMMATRIX3X4FVPROC glad_glUniformMatrix3x4fv
Referenced by load_GL_VERSION_2_1.
PFNGLUNIFORMMATRIX4DVPROC glad_glUniformMatrix4dv
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORMMATRIX4FVPROC glad_glUniformMatrix4fv
Referenced by load_GL_VERSION_2_0.
PFNGLUNIFORMMATRIX4X2DVPROC glad_glUniformMatrix4x2dv
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORMMATRIX4X2FVPROC glad_glUniformMatrix4x2fv
Referenced by load_GL_VERSION_2_1.
PFNGLUNIFORMMATRIX4X3DVPROC glad_glUniformMatrix4x3dv
Referenced by load_GL_VERSION_4_0.
PFNGLUNIFORMMATRIX4X3FVPROC glad_glUniformMatrix4x3fv
Referenced by load_GL_VERSION_2_1.
PFNGLUNIFORMSUBROUTINESUIVPROC glad_glUniformSubroutinesuiv
Referenced by load_GL_VERSION_4_0.
PFNGLUNMAPBUFFERPROC glad_glUnmapBuffer
Referenced by load_GL_VERSION_1_5.
PFNGLUNMAPNAMEDBUFFERPROC glad_glUnmapNamedBuffer
Referenced by load_GL_VERSION_4_5.
PFNGLUSEPROGRAMPROC glad_glUseProgram
Referenced by load_GL_VERSION_2_0.
PFNGLUSEPROGRAMSTAGESPROC glad_glUseProgramStages
Referenced by load_GL_VERSION_4_1.
PFNGLVALIDATEPROGRAMPROC glad_glValidateProgram
Referenced by load_GL_VERSION_2_0.
PFNGLVALIDATEPROGRAMPIPELINEPROC glad_glValidateProgramPipeline
Referenced by load_GL_VERSION_4_1.
PFNGLVERTEX2DPROC glad_glVertex2d
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX2DVPROC glad_glVertex2dv
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX2FPROC glad_glVertex2f
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX2FVPROC glad_glVertex2fv
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX2IPROC glad_glVertex2i
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX2IVPROC glad_glVertex2iv
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX2SPROC glad_glVertex2s
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX2SVPROC glad_glVertex2sv
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX3DPROC glad_glVertex3d
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX3DVPROC glad_glVertex3dv
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX3FPROC glad_glVertex3f
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX3FVPROC glad_glVertex3fv
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX3IPROC glad_glVertex3i
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX3IVPROC glad_glVertex3iv
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX3SPROC glad_glVertex3s
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX3SVPROC glad_glVertex3sv
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX4DPROC glad_glVertex4d
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX4DVPROC glad_glVertex4dv
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX4FPROC glad_glVertex4f
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX4FVPROC glad_glVertex4fv
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX4IPROC glad_glVertex4i
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX4IVPROC glad_glVertex4iv
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX4SPROC glad_glVertex4s
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEX4SVPROC glad_glVertex4sv
Referenced by load_GL_VERSION_1_0.
PFNGLVERTEXARRAYATTRIBBINDINGPROC glad_glVertexArrayAttribBinding
Referenced by load_GL_VERSION_4_5.
PFNGLVERTEXARRAYATTRIBFORMATPROC glad_glVertexArrayAttribFormat
Referenced by load_GL_VERSION_4_5.
PFNGLVERTEXARRAYATTRIBIFORMATPROC glad_glVertexArrayAttribIFormat
Referenced by load_GL_VERSION_4_5.
PFNGLVERTEXARRAYATTRIBLFORMATPROC glad_glVertexArrayAttribLFormat
Referenced by load_GL_VERSION_4_5.
PFNGLVERTEXARRAYBINDINGDIVISORPROC glad_glVertexArrayBindingDivisor
Referenced by load_GL_VERSION_4_5.
PFNGLVERTEXARRAYELEMENTBUFFERPROC glad_glVertexArrayElementBuffer
Referenced by load_GL_VERSION_4_5.
PFNGLVERTEXARRAYVERTEXBUFFERPROC glad_glVertexArrayVertexBuffer
Referenced by load_GL_VERSION_4_5.
PFNGLVERTEXARRAYVERTEXBUFFERSPROC glad_glVertexArrayVertexBuffers
Referenced by load_GL_VERSION_4_5.
PFNGLVERTEXATTRIB1DPROC glad_glVertexAttrib1d
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB1DVPROC glad_glVertexAttrib1dv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB1FPROC glad_glVertexAttrib1f
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB1FVPROC glad_glVertexAttrib1fv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB1SPROC glad_glVertexAttrib1s
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB1SVPROC glad_glVertexAttrib1sv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB2DPROC glad_glVertexAttrib2d
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB2DVPROC glad_glVertexAttrib2dv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB2FPROC glad_glVertexAttrib2f
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB2FVPROC glad_glVertexAttrib2fv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB2SPROC glad_glVertexAttrib2s
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB2SVPROC glad_glVertexAttrib2sv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB3DPROC glad_glVertexAttrib3d
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB3DVPROC glad_glVertexAttrib3dv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB3FPROC glad_glVertexAttrib3f
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB3FVPROC glad_glVertexAttrib3fv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB3SPROC glad_glVertexAttrib3s
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB3SVPROC glad_glVertexAttrib3sv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4NBVPROC glad_glVertexAttrib4Nbv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4NIVPROC glad_glVertexAttrib4Niv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4NSVPROC glad_glVertexAttrib4Nsv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4NUBPROC glad_glVertexAttrib4Nub
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4NUBVPROC glad_glVertexAttrib4Nubv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4NUIVPROC glad_glVertexAttrib4Nuiv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4NUSVPROC glad_glVertexAttrib4Nusv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4BVPROC glad_glVertexAttrib4bv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4DPROC glad_glVertexAttrib4d
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4DVPROC glad_glVertexAttrib4dv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4FPROC glad_glVertexAttrib4f
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4FVPROC glad_glVertexAttrib4fv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4IVPROC glad_glVertexAttrib4iv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4SPROC glad_glVertexAttrib4s
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4SVPROC glad_glVertexAttrib4sv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4UBVPROC glad_glVertexAttrib4ubv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4UIVPROC glad_glVertexAttrib4uiv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIB4USVPROC glad_glVertexAttrib4usv
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXATTRIBBINDINGPROC glad_glVertexAttribBinding
Referenced by load_GL_VERSION_4_3.
PFNGLVERTEXATTRIBDIVISORPROC glad_glVertexAttribDivisor
Referenced by load_GL_VERSION_3_3.
PFNGLVERTEXATTRIBFORMATPROC glad_glVertexAttribFormat
Referenced by load_GL_VERSION_4_3.
PFNGLVERTEXATTRIBI1IPROC glad_glVertexAttribI1i
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI1IVPROC glad_glVertexAttribI1iv
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI1UIPROC glad_glVertexAttribI1ui
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI1UIVPROC glad_glVertexAttribI1uiv
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI2IPROC glad_glVertexAttribI2i
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI2IVPROC glad_glVertexAttribI2iv
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI2UIPROC glad_glVertexAttribI2ui
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI2UIVPROC glad_glVertexAttribI2uiv
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI3IPROC glad_glVertexAttribI3i
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI3IVPROC glad_glVertexAttribI3iv
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI3UIPROC glad_glVertexAttribI3ui
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI3UIVPROC glad_glVertexAttribI3uiv
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI4BVPROC glad_glVertexAttribI4bv
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI4IPROC glad_glVertexAttribI4i
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI4IVPROC glad_glVertexAttribI4iv
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI4SVPROC glad_glVertexAttribI4sv
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI4UBVPROC glad_glVertexAttribI4ubv
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI4UIPROC glad_glVertexAttribI4ui
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI4UIVPROC glad_glVertexAttribI4uiv
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBI4USVPROC glad_glVertexAttribI4usv
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBIFORMATPROC glad_glVertexAttribIFormat
Referenced by load_GL_VERSION_4_3.
PFNGLVERTEXATTRIBIPOINTERPROC glad_glVertexAttribIPointer
Referenced by load_GL_VERSION_3_0.
PFNGLVERTEXATTRIBL1DPROC glad_glVertexAttribL1d
Referenced by load_GL_VERSION_4_1.
PFNGLVERTEXATTRIBL1DVPROC glad_glVertexAttribL1dv
Referenced by load_GL_VERSION_4_1.
PFNGLVERTEXATTRIBL2DPROC glad_glVertexAttribL2d
Referenced by load_GL_VERSION_4_1.
PFNGLVERTEXATTRIBL2DVPROC glad_glVertexAttribL2dv
Referenced by load_GL_VERSION_4_1.
PFNGLVERTEXATTRIBL3DPROC glad_glVertexAttribL3d
Referenced by load_GL_VERSION_4_1.
PFNGLVERTEXATTRIBL3DVPROC glad_glVertexAttribL3dv
Referenced by load_GL_VERSION_4_1.
PFNGLVERTEXATTRIBL4DPROC glad_glVertexAttribL4d
Referenced by load_GL_VERSION_4_1.
PFNGLVERTEXATTRIBL4DVPROC glad_glVertexAttribL4dv
Referenced by load_GL_VERSION_4_1.
PFNGLVERTEXATTRIBLFORMATPROC glad_glVertexAttribLFormat
Referenced by load_GL_VERSION_4_3.
PFNGLVERTEXATTRIBLPOINTERPROC glad_glVertexAttribLPointer
Referenced by load_GL_VERSION_4_1.
PFNGLVERTEXATTRIBP1UIPROC glad_glVertexAttribP1ui
Referenced by load_GL_VERSION_3_3.
PFNGLVERTEXATTRIBP1UIVPROC glad_glVertexAttribP1uiv
Referenced by load_GL_VERSION_3_3.
PFNGLVERTEXATTRIBP2UIPROC glad_glVertexAttribP2ui
Referenced by load_GL_VERSION_3_3.
PFNGLVERTEXATTRIBP2UIVPROC glad_glVertexAttribP2uiv
Referenced by load_GL_VERSION_3_3.
PFNGLVERTEXATTRIBP3UIPROC glad_glVertexAttribP3ui
Referenced by load_GL_VERSION_3_3.
PFNGLVERTEXATTRIBP3UIVPROC glad_glVertexAttribP3uiv
Referenced by load_GL_VERSION_3_3.
PFNGLVERTEXATTRIBP4UIPROC glad_glVertexAttribP4ui
Referenced by load_GL_VERSION_3_3.
PFNGLVERTEXATTRIBP4UIVPROC glad_glVertexAttribP4uiv
Referenced by load_GL_VERSION_3_3.
PFNGLVERTEXATTRIBPOINTERPROC glad_glVertexAttribPointer
Referenced by load_GL_VERSION_2_0.
PFNGLVERTEXBINDINGDIVISORPROC glad_glVertexBindingDivisor
Referenced by load_GL_VERSION_4_3.
PFNGLVERTEXP2UIPROC glad_glVertexP2ui
Referenced by load_GL_VERSION_3_3.
PFNGLVERTEXP2UIVPROC glad_glVertexP2uiv
Referenced by load_GL_VERSION_3_3.
PFNGLVERTEXP3UIPROC glad_glVertexP3ui
Referenced by load_GL_VERSION_3_3.
PFNGLVERTEXP3UIVPROC glad_glVertexP3uiv
Referenced by load_GL_VERSION_3_3.
PFNGLVERTEXP4UIPROC glad_glVertexP4ui
Referenced by load_GL_VERSION_3_3.
PFNGLVERTEXP4UIVPROC glad_glVertexP4uiv
Referenced by load_GL_VERSION_3_3.
PFNGLVERTEXPOINTERPROC glad_glVertexPointer
Referenced by load_GL_VERSION_1_1.
PFNGLVIEWPORTPROC glad_glViewport
Referenced by load_GL_VERSION_1_0.
PFNGLVIEWPORTARRAYVPROC glad_glViewportArrayv
Referenced by load_GL_VERSION_4_1.
PFNGLVIEWPORTINDEXEDFPROC glad_glViewportIndexedf
Referenced by load_GL_VERSION_4_1.
PFNGLVIEWPORTINDEXEDFVPROC glad_glViewportIndexedfv
Referenced by load_GL_VERSION_4_1.
PFNGLWAITSYNCPROC glad_glWaitSync
Referenced by load_GL_VERSION_3_2.
PFNGLWINDOWPOS2DPROC glad_glWindowPos2d
Referenced by load_GL_VERSION_1_4.
PFNGLWINDOWPOS2DVPROC glad_glWindowPos2dv
Referenced by load_GL_VERSION_1_4.
PFNGLWINDOWPOS2FPROC glad_glWindowPos2f
Referenced by load_GL_VERSION_1_4.
PFNGLWINDOWPOS2FVPROC glad_glWindowPos2fv
Referenced by load_GL_VERSION_1_4.
PFNGLWINDOWPOS2IPROC glad_glWindowPos2i
Referenced by load_GL_VERSION_1_4.
PFNGLWINDOWPOS2IVPROC glad_glWindowPos2iv
Referenced by load_GL_VERSION_1_4.
PFNGLWINDOWPOS2SPROC glad_glWindowPos2s
Referenced by load_GL_VERSION_1_4.
PFNGLWINDOWPOS2SVPROC glad_glWindowPos2sv
Referenced by load_GL_VERSION_1_4.
PFNGLWINDOWPOS3DPROC glad_glWindowPos3d
Referenced by load_GL_VERSION_1_4.
PFNGLWINDOWPOS3DVPROC glad_glWindowPos3dv
Referenced by load_GL_VERSION_1_4.
PFNGLWINDOWPOS3FPROC glad_glWindowPos3f
Referenced by load_GL_VERSION_1_4.
PFNGLWINDOWPOS3FVPROC glad_glWindowPos3fv
Referenced by load_GL_VERSION_1_4.
PFNGLWINDOWPOS3IPROC glad_glWindowPos3i
Referenced by load_GL_VERSION_1_4.
PFNGLWINDOWPOS3IVPROC glad_glWindowPos3iv
Referenced by load_GL_VERSION_1_4.
PFNGLWINDOWPOS3SPROC glad_glWindowPos3s
Referenced by load_GL_VERSION_1_4.
PFNGLWINDOWPOS3SVPROC glad_glWindowPos3sv
Referenced by load_GL_VERSION_1_4.
static void * get_proc(const char *namez)
References gladGetProcAddressPtr, libGL.
Referenced by gladLoadGL.
static int open_gl(void)
References gladGetProcAddressPtr, libGL.
Referenced by gladLoadGL.
static void close_gl(void)
References libGL.
Referenced by gladLoadGL.
int gladLoadGL(void)
References close_gl, get_proc, gladLoadGLLoader, open_gl.
static int get_exts(void)
References exts, exts_i, max_loaded_major, num_exts_i.
Referenced by find_extensionsGL.
static void free_exts(void)
References exts_i, num_exts_i.
Referenced by find_extensionsGL.
static int has_ext(const char *ext)
References exts, exts_i, max_loaded_major, num_exts_i.
Referenced by find_extensionsGL.
static void load_GL_VERSION_1_0(GLADloadproc load)
References GLAD_GL_VERSION_1_0, glad_glAccum, glad_glAlphaFunc, glad_glBegin, glad_glBitmap, glad_glBlendFunc, glad_glCallList, glad_glCallLists, glad_glClear, glad_glClearAccum, glad_glClearColor, glad_glClearDepth, glad_glClearIndex, glad_glClearStencil, glad_glClipPlane, glad_glColor3b, glad_glColor3bv, glad_glColor3d, glad_glColor3dv, glad_glColor3f, glad_glColor3fv, glad_glColor3i, glad_glColor3iv, glad_glColor3s, glad_glColor3sv, glad_glColor3ub, glad_glColor3ubv, glad_glColor3ui, glad_glColor3uiv, glad_glColor3us, glad_glColor3usv, glad_glColor4b, glad_glColor4bv, glad_glColor4d, glad_glColor4dv, glad_glColor4f, glad_glColor4fv, glad_glColor4i, glad_glColor4iv, glad_glColor4s, glad_glColor4sv, glad_glColor4ub, glad_glColor4ubv, glad_glColor4ui, glad_glColor4uiv, glad_glColor4us, glad_glColor4usv, glad_glColorMask, glad_glColorMaterial, glad_glCopyPixels, glad_glCullFace, glad_glDeleteLists, glad_glDepthFunc, glad_glDepthMask, glad_glDepthRange, glad_glDisable, glad_glDrawBuffer, glad_glDrawPixels, glad_glEdgeFlag, glad_glEdgeFlagv, glad_glEnable, glad_glEnd, glad_glEndList, glad_glEvalCoord1d, glad_glEvalCoord1dv, glad_glEvalCoord1f, glad_glEvalCoord1fv, glad_glEvalCoord2d, glad_glEvalCoord2dv, glad_glEvalCoord2f, glad_glEvalCoord2fv, glad_glEvalMesh1, glad_glEvalMesh2, glad_glEvalPoint1, glad_glEvalPoint2, glad_glFeedbackBuffer, glad_glFinish, glad_glFlush, glad_glFogf, glad_glFogfv, glad_glFogi, glad_glFogiv, glad_glFrontFace, glad_glFrustum, glad_glGenLists, glad_glGetBooleanv, glad_glGetClipPlane, glad_glGetDoublev, glad_glGetError, glad_glGetFloatv, glad_glGetIntegerv, glad_glGetLightfv, glad_glGetLightiv, glad_glGetMapdv, glad_glGetMapfv, glad_glGetMapiv, glad_glGetMaterialfv, glad_glGetMaterialiv, glad_glGetPixelMapfv, glad_glGetPixelMapuiv, glad_glGetPixelMapusv, glad_glGetPolygonStipple, glad_glGetString, glad_glGetTexEnvfv, glad_glGetTexEnviv, glad_glGetTexGendv, glad_glGetTexGenfv, glad_glGetTexGeniv, glad_glGetTexImage, glad_glGetTexLevelParameterfv, glad_glGetTexLevelParameteriv, glad_glGetTexParameterfv, glad_glGetTexParameteriv, glad_glHint, glad_glIndexd, glad_glIndexdv, glad_glIndexf, glad_glIndexfv, glad_glIndexi, glad_glIndexiv, glad_glIndexMask, glad_glIndexs, glad_glIndexsv, glad_glInitNames, glad_glIsEnabled, glad_glIsList, glad_glLightf, glad_glLightfv, glad_glLighti, glad_glLightiv, glad_glLightModelf, glad_glLightModelfv, glad_glLightModeli, glad_glLightModeliv, glad_glLineStipple, glad_glLineWidth, glad_glListBase, glad_glLoadIdentity, glad_glLoadMatrixd, glad_glLoadMatrixf, glad_glLoadName, glad_glLogicOp, glad_glMap1d, glad_glMap1f, glad_glMap2d, glad_glMap2f, glad_glMapGrid1d, glad_glMapGrid1f, glad_glMapGrid2d, glad_glMapGrid2f, glad_glMaterialf, glad_glMaterialfv, glad_glMateriali, glad_glMaterialiv, glad_glMatrixMode, glad_glMultMatrixd, glad_glMultMatrixf, glad_glNewList, glad_glNormal3b, glad_glNormal3bv, glad_glNormal3d, glad_glNormal3dv, glad_glNormal3f, glad_glNormal3fv, glad_glNormal3i, glad_glNormal3iv, glad_glNormal3s, glad_glNormal3sv, glad_glOrtho, glad_glPassThrough, glad_glPixelMapfv, glad_glPixelMapuiv, glad_glPixelMapusv, glad_glPixelStoref, glad_glPixelStorei, glad_glPixelTransferf, glad_glPixelTransferi, glad_glPixelZoom, glad_glPointSize, glad_glPolygonMode, glad_glPolygonStipple, glad_glPopAttrib, glad_glPopMatrix, glad_glPopName, glad_glPushAttrib, glad_glPushMatrix, glad_glPushName, glad_glRasterPos2d, glad_glRasterPos2dv, glad_glRasterPos2f, glad_glRasterPos2fv, glad_glRasterPos2i, glad_glRasterPos2iv, glad_glRasterPos2s, glad_glRasterPos2sv, glad_glRasterPos3d, glad_glRasterPos3dv, glad_glRasterPos3f, glad_glRasterPos3fv, glad_glRasterPos3i, glad_glRasterPos3iv, glad_glRasterPos3s, glad_glRasterPos3sv, glad_glRasterPos4d, glad_glRasterPos4dv, glad_glRasterPos4f, glad_glRasterPos4fv, glad_glRasterPos4i, glad_glRasterPos4iv, glad_glRasterPos4s, glad_glRasterPos4sv, glad_glReadBuffer, glad_glReadPixels, glad_glRectd, glad_glRectdv, glad_glRectf, glad_glRectfv, glad_glRecti, glad_glRectiv, glad_glRects, glad_glRectsv, glad_glRenderMode, glad_glRotated, glad_glRotatef, glad_glScaled, glad_glScalef, glad_glScissor, glad_glSelectBuffer, glad_glShadeModel, glad_glStencilFunc, glad_glStencilMask, glad_glStencilOp, glad_glTexCoord1d, glad_glTexCoord1dv, glad_glTexCoord1f, glad_glTexCoord1fv, glad_glTexCoord1i, glad_glTexCoord1iv, glad_glTexCoord1s, glad_glTexCoord1sv, glad_glTexCoord2d, glad_glTexCoord2dv, glad_glTexCoord2f, glad_glTexCoord2fv, glad_glTexCoord2i, glad_glTexCoord2iv, glad_glTexCoord2s, glad_glTexCoord2sv, glad_glTexCoord3d, glad_glTexCoord3dv, glad_glTexCoord3f, glad_glTexCoord3fv, glad_glTexCoord3i, glad_glTexCoord3iv, glad_glTexCoord3s, glad_glTexCoord3sv, glad_glTexCoord4d, glad_glTexCoord4dv, glad_glTexCoord4f, glad_glTexCoord4fv, glad_glTexCoord4i, glad_glTexCoord4iv, glad_glTexCoord4s, glad_glTexCoord4sv, glad_glTexEnvf, glad_glTexEnvfv, glad_glTexEnvi, glad_glTexEnviv, glad_glTexGend, glad_glTexGendv, glad_glTexGenf, glad_glTexGenfv, glad_glTexGeni, glad_glTexGeniv, glad_glTexImage1D, glad_glTexImage2D, glad_glTexParameterf, glad_glTexParameterfv, glad_glTexParameteri, glad_glTexParameteriv, glad_glTranslated, glad_glTranslatef, glad_glVertex2d, glad_glVertex2dv, glad_glVertex2f, glad_glVertex2fv, glad_glVertex2i, glad_glVertex2iv, glad_glVertex2s, glad_glVertex2sv, glad_glVertex3d, glad_glVertex3dv, glad_glVertex3f, glad_glVertex3fv, glad_glVertex3i, glad_glVertex3iv, glad_glVertex3s, glad_glVertex3sv, glad_glVertex4d, glad_glVertex4dv, glad_glVertex4f, glad_glVertex4fv, glad_glVertex4i, glad_glVertex4iv, glad_glVertex4s, glad_glVertex4sv, glad_glViewport.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_1_1(GLADloadproc load)
References GLAD_GL_VERSION_1_1, glad_glAreTexturesResident, glad_glArrayElement, glad_glBindTexture, glad_glColorPointer, glad_glCopyTexImage1D, glad_glCopyTexImage2D, glad_glCopyTexSubImage1D, glad_glCopyTexSubImage2D, glad_glDeleteTextures, glad_glDisableClientState, glad_glDrawArrays, glad_glDrawElements, glad_glEdgeFlagPointer, glad_glEnableClientState, glad_glGenTextures, glad_glGetPointerv, glad_glIndexPointer, glad_glIndexub, glad_glIndexubv, glad_glInterleavedArrays, glad_glIsTexture, glad_glNormalPointer, glad_glPolygonOffset, glad_glPopClientAttrib, glad_glPrioritizeTextures, glad_glPushClientAttrib, glad_glTexCoordPointer, glad_glTexSubImage1D, glad_glTexSubImage2D, glad_glVertexPointer.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_1_2(GLADloadproc load)
References GLAD_GL_VERSION_1_2, glad_glCopyTexSubImage3D, glad_glDrawRangeElements, glad_glTexImage3D, glad_glTexSubImage3D.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_1_3(GLADloadproc load)
References GLAD_GL_VERSION_1_3, glad_glActiveTexture, glad_glClientActiveTexture, glad_glCompressedTexImage1D, glad_glCompressedTexImage2D, glad_glCompressedTexImage3D, glad_glCompressedTexSubImage1D, glad_glCompressedTexSubImage2D, glad_glCompressedTexSubImage3D, glad_glGetCompressedTexImage, glad_glLoadTransposeMatrixd, glad_glLoadTransposeMatrixf, glad_glMultiTexCoord1d, glad_glMultiTexCoord1dv, glad_glMultiTexCoord1f, glad_glMultiTexCoord1fv, glad_glMultiTexCoord1i, glad_glMultiTexCoord1iv, glad_glMultiTexCoord1s, glad_glMultiTexCoord1sv, glad_glMultiTexCoord2d, glad_glMultiTexCoord2dv, glad_glMultiTexCoord2f, glad_glMultiTexCoord2fv, glad_glMultiTexCoord2i, glad_glMultiTexCoord2iv, glad_glMultiTexCoord2s, glad_glMultiTexCoord2sv, glad_glMultiTexCoord3d, glad_glMultiTexCoord3dv, glad_glMultiTexCoord3f, glad_glMultiTexCoord3fv, glad_glMultiTexCoord3i, glad_glMultiTexCoord3iv, glad_glMultiTexCoord3s, glad_glMultiTexCoord3sv, glad_glMultiTexCoord4d, glad_glMultiTexCoord4dv, glad_glMultiTexCoord4f, glad_glMultiTexCoord4fv, glad_glMultiTexCoord4i, glad_glMultiTexCoord4iv, glad_glMultiTexCoord4s, glad_glMultiTexCoord4sv, glad_glMultTransposeMatrixd, glad_glMultTransposeMatrixf, glad_glSampleCoverage.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_1_4(GLADloadproc load)
References GLAD_GL_VERSION_1_4, glad_glBlendColor, glad_glBlendEquation, glad_glBlendFuncSeparate, glad_glFogCoordd, glad_glFogCoorddv, glad_glFogCoordf, glad_glFogCoordfv, glad_glFogCoordPointer, glad_glMultiDrawArrays, glad_glMultiDrawElements, glad_glPointParameterf, glad_glPointParameterfv, glad_glPointParameteri, glad_glPointParameteriv, glad_glSecondaryColor3b, glad_glSecondaryColor3bv, glad_glSecondaryColor3d, glad_glSecondaryColor3dv, glad_glSecondaryColor3f, glad_glSecondaryColor3fv, glad_glSecondaryColor3i, glad_glSecondaryColor3iv, glad_glSecondaryColor3s, glad_glSecondaryColor3sv, glad_glSecondaryColor3ub, glad_glSecondaryColor3ubv, glad_glSecondaryColor3ui, glad_glSecondaryColor3uiv, glad_glSecondaryColor3us, glad_glSecondaryColor3usv, glad_glSecondaryColorPointer, glad_glWindowPos2d, glad_glWindowPos2dv, glad_glWindowPos2f, glad_glWindowPos2fv, glad_glWindowPos2i, glad_glWindowPos2iv, glad_glWindowPos2s, glad_glWindowPos2sv, glad_glWindowPos3d, glad_glWindowPos3dv, glad_glWindowPos3f, glad_glWindowPos3fv, glad_glWindowPos3i, glad_glWindowPos3iv, glad_glWindowPos3s, glad_glWindowPos3sv.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_1_5(GLADloadproc load)
References GLAD_GL_VERSION_1_5, glad_glBeginQuery, glad_glBindBuffer, glad_glBufferData, glad_glBufferSubData, glad_glDeleteBuffers, glad_glDeleteQueries, glad_glEndQuery, glad_glGenBuffers, glad_glGenQueries, glad_glGetBufferParameteriv, glad_glGetBufferPointerv, glad_glGetBufferSubData, glad_glGetQueryiv, glad_glGetQueryObjectiv, glad_glGetQueryObjectuiv, glad_glIsBuffer, glad_glIsQuery, glad_glMapBuffer, glad_glUnmapBuffer.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_2_0(GLADloadproc load)
References GLAD_GL_VERSION_2_0, glad_glAttachShader, glad_glBindAttribLocation, glad_glBlendEquationSeparate, glad_glCompileShader, glad_glCreateProgram, glad_glCreateShader, glad_glDeleteProgram, glad_glDeleteShader, glad_glDetachShader, glad_glDisableVertexAttribArray, glad_glDrawBuffers, glad_glEnableVertexAttribArray, glad_glGetActiveAttrib, glad_glGetActiveUniform, glad_glGetAttachedShaders, glad_glGetAttribLocation, glad_glGetProgramInfoLog, glad_glGetProgramiv, glad_glGetShaderInfoLog, glad_glGetShaderiv, glad_glGetShaderSource, glad_glGetUniformfv, glad_glGetUniformiv, glad_glGetUniformLocation, glad_glGetVertexAttribdv, glad_glGetVertexAttribfv, glad_glGetVertexAttribiv, glad_glGetVertexAttribPointerv, glad_glIsProgram, glad_glIsShader, glad_glLinkProgram, glad_glShaderSource, glad_glStencilFuncSeparate, glad_glStencilMaskSeparate, glad_glStencilOpSeparate, glad_glUniform1f, glad_glUniform1fv, glad_glUniform1i, glad_glUniform1iv, glad_glUniform2f, glad_glUniform2fv, glad_glUniform2i, glad_glUniform2iv, glad_glUniform3f, glad_glUniform3fv, glad_glUniform3i, glad_glUniform3iv, glad_glUniform4f, glad_glUniform4fv, glad_glUniform4i, glad_glUniform4iv, glad_glUniformMatrix2fv, glad_glUniformMatrix3fv, glad_glUniformMatrix4fv, glad_glUseProgram, glad_glValidateProgram, glad_glVertexAttrib1d, glad_glVertexAttrib1dv, glad_glVertexAttrib1f, glad_glVertexAttrib1fv, glad_glVertexAttrib1s, glad_glVertexAttrib1sv, glad_glVertexAttrib2d, glad_glVertexAttrib2dv, glad_glVertexAttrib2f, glad_glVertexAttrib2fv, glad_glVertexAttrib2s, glad_glVertexAttrib2sv, glad_glVertexAttrib3d, glad_glVertexAttrib3dv, glad_glVertexAttrib3f, glad_glVertexAttrib3fv, glad_glVertexAttrib3s, glad_glVertexAttrib3sv, glad_glVertexAttrib4bv, glad_glVertexAttrib4d, glad_glVertexAttrib4dv, glad_glVertexAttrib4f, glad_glVertexAttrib4fv, glad_glVertexAttrib4iv, glad_glVertexAttrib4Nbv, glad_glVertexAttrib4Niv, glad_glVertexAttrib4Nsv, glad_glVertexAttrib4Nub, glad_glVertexAttrib4Nubv, glad_glVertexAttrib4Nuiv, glad_glVertexAttrib4Nusv, glad_glVertexAttrib4s, glad_glVertexAttrib4sv, glad_glVertexAttrib4ubv, glad_glVertexAttrib4uiv, glad_glVertexAttrib4usv, glad_glVertexAttribPointer.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_2_1(GLADloadproc load)
References GLAD_GL_VERSION_2_1, glad_glUniformMatrix2x3fv, glad_glUniformMatrix2x4fv, glad_glUniformMatrix3x2fv, glad_glUniformMatrix3x4fv, glad_glUniformMatrix4x2fv, glad_glUniformMatrix4x3fv.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_3_0(GLADloadproc load)
References GLAD_GL_VERSION_3_0, glad_glBeginConditionalRender, glad_glBeginTransformFeedback, glad_glBindBufferBase, glad_glBindBufferRange, glad_glBindFragDataLocation, glad_glBindFramebuffer, glad_glBindRenderbuffer, glad_glBindVertexArray, glad_glBlitFramebuffer, glad_glCheckFramebufferStatus, glad_glClampColor, glad_glClearBufferfi, glad_glClearBufferfv, glad_glClearBufferiv, glad_glClearBufferuiv, glad_glColorMaski, glad_glDeleteFramebuffers, glad_glDeleteRenderbuffers, glad_glDeleteVertexArrays, glad_glDisablei, glad_glEnablei, glad_glEndConditionalRender, glad_glEndTransformFeedback, glad_glFlushMappedBufferRange, glad_glFramebufferRenderbuffer, glad_glFramebufferTexture1D, glad_glFramebufferTexture2D, glad_glFramebufferTexture3D, glad_glFramebufferTextureLayer, glad_glGenerateMipmap, glad_glGenFramebuffers, glad_glGenRenderbuffers, glad_glGenVertexArrays, glad_glGetBooleani_v, glad_glGetFragDataLocation, glad_glGetFramebufferAttachmentParameteriv, glad_glGetIntegeri_v, glad_glGetRenderbufferParameteriv, glad_glGetStringi, glad_glGetTexParameterIiv, glad_glGetTexParameterIuiv, glad_glGetTransformFeedbackVarying, glad_glGetUniformuiv, glad_glGetVertexAttribIiv, glad_glGetVertexAttribIuiv, glad_glIsEnabledi, glad_glIsFramebuffer, glad_glIsRenderbuffer, glad_glIsVertexArray, glad_glMapBufferRange, glad_glRenderbufferStorage, glad_glRenderbufferStorageMultisample, glad_glTexParameterIiv, glad_glTexParameterIuiv, glad_glTransformFeedbackVaryings, glad_glUniform1ui, glad_glUniform1uiv, glad_glUniform2ui, glad_glUniform2uiv, glad_glUniform3ui, glad_glUniform3uiv, glad_glUniform4ui, glad_glUniform4uiv, glad_glVertexAttribI1i, glad_glVertexAttribI1iv, glad_glVertexAttribI1ui, glad_glVertexAttribI1uiv, glad_glVertexAttribI2i, glad_glVertexAttribI2iv, glad_glVertexAttribI2ui, glad_glVertexAttribI2uiv, glad_glVertexAttribI3i, glad_glVertexAttribI3iv, glad_glVertexAttribI3ui, glad_glVertexAttribI3uiv, glad_glVertexAttribI4bv, glad_glVertexAttribI4i, glad_glVertexAttribI4iv, glad_glVertexAttribI4sv, glad_glVertexAttribI4ubv, glad_glVertexAttribI4ui, glad_glVertexAttribI4uiv, glad_glVertexAttribI4usv, glad_glVertexAttribIPointer.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_3_1(GLADloadproc load)
References GLAD_GL_VERSION_3_1, glad_glBindBufferBase, glad_glBindBufferRange, glad_glCopyBufferSubData, glad_glDrawArraysInstanced, glad_glDrawElementsInstanced, glad_glGetActiveUniformBlockiv, glad_glGetActiveUniformBlockName, glad_glGetActiveUniformName, glad_glGetActiveUniformsiv, glad_glGetIntegeri_v, glad_glGetUniformBlockIndex, glad_glGetUniformIndices, glad_glPrimitiveRestartIndex, glad_glTexBuffer, glad_glUniformBlockBinding.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_3_2(GLADloadproc load)
References GLAD_GL_VERSION_3_2, glad_glClientWaitSync, glad_glDeleteSync, glad_glDrawElementsBaseVertex, glad_glDrawElementsInstancedBaseVertex, glad_glDrawRangeElementsBaseVertex, glad_glFenceSync, glad_glFramebufferTexture, glad_glGetBufferParameteri64v, glad_glGetInteger64i_v, glad_glGetInteger64v, glad_glGetMultisamplefv, glad_glGetSynciv, glad_glIsSync, glad_glMultiDrawElementsBaseVertex, glad_glProvokingVertex, glad_glSampleMaski, glad_glTexImage2DMultisample, glad_glTexImage3DMultisample, glad_glWaitSync.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_3_3(GLADloadproc load)
References GLAD_GL_VERSION_3_3, glad_glBindFragDataLocationIndexed, glad_glBindSampler, glad_glColorP3ui, glad_glColorP3uiv, glad_glColorP4ui, glad_glColorP4uiv, glad_glDeleteSamplers, glad_glGenSamplers, glad_glGetFragDataIndex, glad_glGetQueryObjecti64v, glad_glGetQueryObjectui64v, glad_glGetSamplerParameterfv, glad_glGetSamplerParameterIiv, glad_glGetSamplerParameterIuiv, glad_glGetSamplerParameteriv, glad_glIsSampler, glad_glMultiTexCoordP1ui, glad_glMultiTexCoordP1uiv, glad_glMultiTexCoordP2ui, glad_glMultiTexCoordP2uiv, glad_glMultiTexCoordP3ui, glad_glMultiTexCoordP3uiv, glad_glMultiTexCoordP4ui, glad_glMultiTexCoordP4uiv, glad_glNormalP3ui, glad_glNormalP3uiv, glad_glQueryCounter, glad_glSamplerParameterf, glad_glSamplerParameterfv, glad_glSamplerParameteri, glad_glSamplerParameterIiv, glad_glSamplerParameterIuiv, glad_glSamplerParameteriv, glad_glSecondaryColorP3ui, glad_glSecondaryColorP3uiv, glad_glTexCoordP1ui, glad_glTexCoordP1uiv, glad_glTexCoordP2ui, glad_glTexCoordP2uiv, glad_glTexCoordP3ui, glad_glTexCoordP3uiv, glad_glTexCoordP4ui, glad_glTexCoordP4uiv, glad_glVertexAttribDivisor, glad_glVertexAttribP1ui, glad_glVertexAttribP1uiv, glad_glVertexAttribP2ui, glad_glVertexAttribP2uiv, glad_glVertexAttribP3ui, glad_glVertexAttribP3uiv, glad_glVertexAttribP4ui, glad_glVertexAttribP4uiv, glad_glVertexP2ui, glad_glVertexP2uiv, glad_glVertexP3ui, glad_glVertexP3uiv, glad_glVertexP4ui, glad_glVertexP4uiv.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_4_0(GLADloadproc load)
References GLAD_GL_VERSION_4_0, glad_glBeginQueryIndexed, glad_glBindTransformFeedback, glad_glBlendEquationi, glad_glBlendEquationSeparatei, glad_glBlendFunci, glad_glBlendFuncSeparatei, glad_glDeleteTransformFeedbacks, glad_glDrawArraysIndirect, glad_glDrawElementsIndirect, glad_glDrawTransformFeedback, glad_glDrawTransformFeedbackStream, glad_glEndQueryIndexed, glad_glGenTransformFeedbacks, glad_glGetActiveSubroutineName, glad_glGetActiveSubroutineUniformiv, glad_glGetActiveSubroutineUniformName, glad_glGetProgramStageiv, glad_glGetQueryIndexediv, glad_glGetSubroutineIndex, glad_glGetSubroutineUniformLocation, glad_glGetUniformdv, glad_glGetUniformSubroutineuiv, glad_glIsTransformFeedback, glad_glMinSampleShading, glad_glPatchParameterfv, glad_glPatchParameteri, glad_glPauseTransformFeedback, glad_glResumeTransformFeedback, glad_glUniform1d, glad_glUniform1dv, glad_glUniform2d, glad_glUniform2dv, glad_glUniform3d, glad_glUniform3dv, glad_glUniform4d, glad_glUniform4dv, glad_glUniformMatrix2dv, glad_glUniformMatrix2x3dv, glad_glUniformMatrix2x4dv, glad_glUniformMatrix3dv, glad_glUniformMatrix3x2dv, glad_glUniformMatrix3x4dv, glad_glUniformMatrix4dv, glad_glUniformMatrix4x2dv, glad_glUniformMatrix4x3dv, glad_glUniformSubroutinesuiv.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_4_1(GLADloadproc load)
References GLAD_GL_VERSION_4_1, glad_glActiveShaderProgram, glad_glBindProgramPipeline, glad_glClearDepthf, glad_glCreateShaderProgramv, glad_glDeleteProgramPipelines, glad_glDepthRangeArrayv, glad_glDepthRangef, glad_glDepthRangeIndexed, glad_glGenProgramPipelines, glad_glGetDoublei_v, glad_glGetFloati_v, glad_glGetProgramBinary, glad_glGetProgramPipelineInfoLog, glad_glGetProgramPipelineiv, glad_glGetShaderPrecisionFormat, glad_glGetVertexAttribLdv, glad_glIsProgramPipeline, glad_glProgramBinary, glad_glProgramParameteri, glad_glProgramUniform1d, glad_glProgramUniform1dv, glad_glProgramUniform1f, glad_glProgramUniform1fv, glad_glProgramUniform1i, glad_glProgramUniform1iv, glad_glProgramUniform1ui, glad_glProgramUniform1uiv, glad_glProgramUniform2d, glad_glProgramUniform2dv, glad_glProgramUniform2f, glad_glProgramUniform2fv, glad_glProgramUniform2i, glad_glProgramUniform2iv, glad_glProgramUniform2ui, glad_glProgramUniform2uiv, glad_glProgramUniform3d, glad_glProgramUniform3dv, glad_glProgramUniform3f, glad_glProgramUniform3fv, glad_glProgramUniform3i, glad_glProgramUniform3iv, glad_glProgramUniform3ui, glad_glProgramUniform3uiv, glad_glProgramUniform4d, glad_glProgramUniform4dv, glad_glProgramUniform4f, glad_glProgramUniform4fv, glad_glProgramUniform4i, glad_glProgramUniform4iv, glad_glProgramUniform4ui, glad_glProgramUniform4uiv, glad_glProgramUniformMatrix2dv, glad_glProgramUniformMatrix2fv, glad_glProgramUniformMatrix2x3dv, glad_glProgramUniformMatrix2x3fv, glad_glProgramUniformMatrix2x4dv, glad_glProgramUniformMatrix2x4fv, glad_glProgramUniformMatrix3dv, glad_glProgramUniformMatrix3fv, glad_glProgramUniformMatrix3x2dv, glad_glProgramUniformMatrix3x2fv, glad_glProgramUniformMatrix3x4dv, glad_glProgramUniformMatrix3x4fv, glad_glProgramUniformMatrix4dv, glad_glProgramUniformMatrix4fv, glad_glProgramUniformMatrix4x2dv, glad_glProgramUniformMatrix4x2fv, glad_glProgramUniformMatrix4x3dv, glad_glProgramUniformMatrix4x3fv, glad_glReleaseShaderCompiler, glad_glScissorArrayv, glad_glScissorIndexed, glad_glScissorIndexedv, glad_glShaderBinary, glad_glUseProgramStages, glad_glValidateProgramPipeline, glad_glVertexAttribL1d, glad_glVertexAttribL1dv, glad_glVertexAttribL2d, glad_glVertexAttribL2dv, glad_glVertexAttribL3d, glad_glVertexAttribL3dv, glad_glVertexAttribL4d, glad_glVertexAttribL4dv, glad_glVertexAttribLPointer, glad_glViewportArrayv, glad_glViewportIndexedf, glad_glViewportIndexedfv.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_4_2(GLADloadproc load)
References GLAD_GL_VERSION_4_2, glad_glBindImageTexture, glad_glDrawArraysInstancedBaseInstance, glad_glDrawElementsInstancedBaseInstance, glad_glDrawElementsInstancedBaseVertexBaseInstance, glad_glDrawTransformFeedbackInstanced, glad_glDrawTransformFeedbackStreamInstanced, glad_glGetActiveAtomicCounterBufferiv, glad_glGetInternalformativ, glad_glMemoryBarrier, glad_glTexStorage1D, glad_glTexStorage2D, glad_glTexStorage3D.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_4_3(GLADloadproc load)
References GLAD_GL_VERSION_4_3, glad_glBindVertexBuffer, glad_glClearBufferData, glad_glClearBufferSubData, glad_glCopyImageSubData, glad_glDebugMessageCallback, glad_glDebugMessageControl, glad_glDebugMessageInsert, glad_glDispatchCompute, glad_glDispatchComputeIndirect, glad_glFramebufferParameteri, glad_glGetDebugMessageLog, glad_glGetFramebufferParameteriv, glad_glGetInternalformati64v, glad_glGetObjectLabel, glad_glGetObjectPtrLabel, glad_glGetPointerv, glad_glGetProgramInterfaceiv, glad_glGetProgramResourceIndex, glad_glGetProgramResourceiv, glad_glGetProgramResourceLocation, glad_glGetProgramResourceLocationIndex, glad_glGetProgramResourceName, glad_glInvalidateBufferData, glad_glInvalidateBufferSubData, glad_glInvalidateFramebuffer, glad_glInvalidateSubFramebuffer, glad_glInvalidateTexImage, glad_glInvalidateTexSubImage, glad_glMultiDrawArraysIndirect, glad_glMultiDrawElementsIndirect, glad_glObjectLabel, glad_glObjectPtrLabel, glad_glPopDebugGroup, glad_glPushDebugGroup, glad_glShaderStorageBlockBinding, glad_glTexBufferRange, glad_glTexStorage2DMultisample, glad_glTexStorage3DMultisample, glad_glTextureView, glad_glVertexAttribBinding, glad_glVertexAttribFormat, glad_glVertexAttribIFormat, glad_glVertexAttribLFormat, glad_glVertexBindingDivisor.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_4_4(GLADloadproc load)
References GLAD_GL_VERSION_4_4, glad_glBindBuffersBase, glad_glBindBuffersRange, glad_glBindImageTextures, glad_glBindSamplers, glad_glBindTextures, glad_glBindVertexBuffers, glad_glBufferStorage, glad_glClearTexImage, glad_glClearTexSubImage.
Referenced by gladLoadGLLoader.
static void load_GL_VERSION_4_5(GLADloadproc load)
References GLAD_GL_VERSION_4_5, glad_glBindTextureUnit, glad_glBlitNamedFramebuffer, glad_glCheckNamedFramebufferStatus, glad_glClearNamedBufferData, glad_glClearNamedBufferSubData, glad_glClearNamedFramebufferfi, glad_glClearNamedFramebufferfv, glad_glClearNamedFramebufferiv, glad_glClearNamedFramebufferuiv, glad_glClipControl, glad_glCompressedTextureSubImage1D, glad_glCompressedTextureSubImage2D, glad_glCompressedTextureSubImage3D, glad_glCopyNamedBufferSubData, glad_glCopyTextureSubImage1D, glad_glCopyTextureSubImage2D, glad_glCopyTextureSubImage3D, glad_glCreateBuffers, glad_glCreateFramebuffers, glad_glCreateProgramPipelines, glad_glCreateQueries, glad_glCreateRenderbuffers, glad_glCreateSamplers, glad_glCreateTextures, glad_glCreateTransformFeedbacks, glad_glCreateVertexArrays, glad_glDisableVertexArrayAttrib, glad_glEnableVertexArrayAttrib, glad_glFlushMappedNamedBufferRange, glad_glGenerateTextureMipmap, glad_glGetCompressedTextureImage, glad_glGetCompressedTextureSubImage, glad_glGetGraphicsResetStatus, glad_glGetNamedBufferParameteri64v, glad_glGetNamedBufferParameteriv, glad_glGetNamedBufferPointerv, glad_glGetNamedBufferSubData, glad_glGetNamedFramebufferAttachmentParameteriv, glad_glGetNamedFramebufferParameteriv, glad_glGetNamedRenderbufferParameteriv, glad_glGetnColorTable, glad_glGetnCompressedTexImage, glad_glGetnConvolutionFilter, glad_glGetnHistogram, glad_glGetnMapdv, glad_glGetnMapfv, glad_glGetnMapiv, glad_glGetnMinmax, glad_glGetnPixelMapfv, glad_glGetnPixelMapuiv, glad_glGetnPixelMapusv, glad_glGetnPolygonStipple, glad_glGetnSeparableFilter, glad_glGetnTexImage, glad_glGetnUniformdv, glad_glGetnUniformfv, glad_glGetnUniformiv, glad_glGetnUniformuiv, glad_glGetQueryBufferObjecti64v, glad_glGetQueryBufferObjectiv, glad_glGetQueryBufferObjectui64v, glad_glGetQueryBufferObjectuiv, glad_glGetTextureImage, glad_glGetTextureLevelParameterfv, glad_glGetTextureLevelParameteriv, glad_glGetTextureParameterfv, glad_glGetTextureParameterIiv, glad_glGetTextureParameterIuiv, glad_glGetTextureParameteriv, glad_glGetTextureSubImage, glad_glGetTransformFeedbacki64_v, glad_glGetTransformFeedbacki_v, glad_glGetTransformFeedbackiv, glad_glGetVertexArrayIndexed64iv, glad_glGetVertexArrayIndexediv, glad_glGetVertexArrayiv, glad_glInvalidateNamedFramebufferData, glad_glInvalidateNamedFramebufferSubData, glad_glMapNamedBuffer, glad_glMapNamedBufferRange, glad_glMemoryBarrierByRegion, glad_glNamedBufferData, glad_glNamedBufferStorage, glad_glNamedBufferSubData, glad_glNamedFramebufferDrawBuffer, glad_glNamedFramebufferDrawBuffers, glad_glNamedFramebufferParameteri, glad_glNamedFramebufferReadBuffer, glad_glNamedFramebufferRenderbuffer, glad_glNamedFramebufferTexture, glad_glNamedFramebufferTextureLayer, glad_glNamedRenderbufferStorage, glad_glNamedRenderbufferStorageMultisample, glad_glReadnPixels, glad_glTextureBarrier, glad_glTextureBuffer, glad_glTextureBufferRange, glad_glTextureParameterf, glad_glTextureParameterfv, glad_glTextureParameteri, glad_glTextureParameterIiv, glad_glTextureParameterIuiv, glad_glTextureParameteriv, glad_glTextureStorage1D, glad_glTextureStorage2D, glad_glTextureStorage2DMultisample, glad_glTextureStorage3D, glad_glTextureStorage3DMultisample, glad_glTextureSubImage1D, glad_glTextureSubImage2D, glad_glTextureSubImage3D, glad_glTransformFeedbackBufferBase, glad_glTransformFeedbackBufferRange, glad_glUnmapNamedBuffer, glad_glVertexArrayAttribBinding, glad_glVertexArrayAttribFormat, glad_glVertexArrayAttribIFormat, glad_glVertexArrayAttribLFormat, glad_glVertexArrayBindingDivisor, glad_glVertexArrayElementBuffer, glad_glVertexArrayVertexBuffer, glad_glVertexArrayVertexBuffers.
Referenced by gladLoadGLLoader.
static int find_extensionsGL(void)
References free_exts, get_exts, has_ext.
Referenced by gladLoadGLLoader.
static void find_coreGL(void)
References GLAD_GL_VERSION_1_0, GLAD_GL_VERSION_1_1, GLAD_GL_VERSION_1_2, GLAD_GL_VERSION_1_3, GLAD_GL_VERSION_1_4, GLAD_GL_VERSION_1_5, GLAD_GL_VERSION_2_0, GLAD_GL_VERSION_2_1, GLAD_GL_VERSION_3_0, GLAD_GL_VERSION_3_1, GLAD_GL_VERSION_3_2, GLAD_GL_VERSION_3_3, GLAD_GL_VERSION_4_0, GLAD_GL_VERSION_4_1, GLAD_GL_VERSION_4_2, GLAD_GL_VERSION_4_3, GLAD_GL_VERSION_4_4, GLAD_GL_VERSION_4_5, GLVersion, max_loaded_major, max_loaded_minor.
Referenced by gladLoadGLLoader.
int gladLoadGLLoader(GLADloadproc load)
References find_coreGL, find_extensionsGL, GLVersion, load_GL_VERSION_1_0, load_GL_VERSION_1_1, load_GL_VERSION_1_2, load_GL_VERSION_1_3, load_GL_VERSION_1_4, load_GL_VERSION_1_5, load_GL_VERSION_2_0, load_GL_VERSION_2_1, load_GL_VERSION_3_0, load_GL_VERSION_3_1, load_GL_VERSION_3_2, load_GL_VERSION_3_3, load_GL_VERSION_4_0, load_GL_VERSION_4_1, load_GL_VERSION_4_2, load_GL_VERSION_4_3, load_GL_VERSION_4_4, load_GL_VERSION_4_5.
Referenced by gladLoadGL, main.